### ISSUE TITLE
Duplicating propTypes ?

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#1]
There is the ESLint rule [prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) which I am using and looks like a good thing. However with `@provide` having separate propTypes this wont work and I would have to duplicate these. 

I guess that pulling propTypes from component constructor instead of having it specified by argument to `@provide` is not an option because there might be other props mixed in which are not about to be provided. Any idea what could be done about this?

**Comment by timbur** [comment]
I personally stopped using ESLint because of running into silly stuff like this entirely too often.  It's too rigid/opinionated for my tastes.  That said, there are 3 options I can think of right now to solve this problem, best options first (in my opinion):

1.  Fix the ESLint `prop-types` rule to look at the resulting (decorated, higher order) component's constructor's `propTypes`.
2.  Disable the `prop-types` rule.
3.  You should be able to simply call `@provide()` without any `propTypes` and merge your provided `propTypes` into your component's `propTypes`.  The reason for passing `propTypes` to `provide()` as a separate object is mainly for explicitness and readability/understandability.  It's to make it obvious to anyone looking at the component which props are expected to be provided by flux/redux as opposed to props provided by parent components.

**Comment by FredyC** [comment]
That's interesting because I find this rule as one of very handy. I have plugin to Sublime Text which immaterially tells me when I use prop which is not on propTypes and thus most likely missing from the pipeline.

Anyway I will try to create issue for that rule and see if there is something possible to do. Frankly I am not sure how does this works, but I thought that static analysis cannot investigate used decorators.

Thanks for help.

**Comment by timbur** [comment]
Hey, as of `4.1.0`, I changed the API for `@provide` so that instead of `@provide(propTypes)` it's just `@provide` and said `propTypes` are merged into the usual `static propTypes = { ... };`.  Can you let me know if that fixes the problem with ESLint?
