### ISSUE TITLE
Data structures, separation of concerns, and replication

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#11]
I don't have any particular issue yet, I am just curious. Since your approach encourages a very good separation of concern (I really like it), various providers may come to light over time from various people. I believe it's not that hard to imagine that some name conflict for an action type name may happen. Suddenly you are dispatching the action and two separate things are happening as a reducers are comparing only _global_ strings, not something that would be private to the provider.

I am wondering if this should be solved somehow internally here? Perhaps it would be nice to include some optional API here to _load_ providers which would allow to consumer to simply say that action types from the particular provider will prefixed with a specified string. Just an idea.

Or is it going to be about provider authors to create their action types with possible name collision in mind? Is everyone really that _polite_ to consider that?

**Comment by timbur** [comment]
The only time you'd ever need to worry about colliding action types is if you're combining providers.  By default, each provider has its own store (lending to an even further separation of concerns), so when an action is dispatched within some provider, only that provider knows about it unless it's combined with other provider(s), and in which case the chances of collision should be close to zero.

From #8: For providers designed around semi-common data structures, you can use provider factories like [`provide-array`](https://github.com/loggur/provide-array) and [`provide-map`](https://github.com/loggur/provide-map), which also allow the action types to easily be unique as well.

As a quick example, with [`provide-array`](https://github.com/loggur/provide-array), you can do this...
```js
import provideArray from 'provide-array';

const list = provideArray();
```
...which will default to `actions` like `filterList`, `pushItem`, etc., `reducers` like `list`, `item`, etc., and its internal action types will be `FILTER_LIST`, etc.

And if you need custom `actions` and `reducers`, you can do this...
```js
import provideArray from 'provide-array';

const awesomeList = provideArray('awesomeList', 'awesomeItem', 'awesomeIndex');
```
...which will then have `actions` like `filterAwesomeList`, `pushAwesomeItem`, etc., `reducers` like `awesomeList`, `awesomeItem`, etc., and its internal action types will be `FILTER_AWESOMELIST`, etc.

**Comment by FredyC** [comment]
To be honest, I did not really started looking into this that deeply. I am in middle of reading your medium articles and I want to start using this in my next project starting next week. I am currently on project using one of the earlier version of Redux and we kinda failíng to follow latest improvements and idea. I will have a lot to catch up.

So essentially in case when there will be just one store, it will still rely on authors of providers. I mean in your case of `provide-array` you clearly had thought about it and included way to customize action names, but not everyone is that forward looking and conflicts may still occur. Wouldn't be better to have some unified way instead of each provider implementing its own logic for customized actions?

**Comment by timbur** [comment]
> So essentially in case when there will be just one store

Do you have an example where this would happen?  With the providers paradigm, keeping everything in one store would be indicative of a design flaw, I think.  It's best to keep things separate, not only for logical concerns and reusability, but for performance as well.

> Wouldn't be better to have some unified way instead of each provider implementing its own logic for customized actions?

I do like the idea of automatically namespacing providers' action types by prefixing the provider's name like `${providerName@@actionType}` or something like that.  :)

My only concern is how it could be done automatically in a way that would allow the following.

Suppose `someProvider` exports its constants like so
```js
export const SOME_CONSTANT = 'SOME_CONSTANT';

const actions = { ... };

const reducers = { ... };

export default { actions, reducers };
```

And then maybe you want to combine that with `anotherProvider` which relies on it:
```js
import { SOME_CONSTANT } from 'someProvider';

const actions = { ... };

const reducers = {
  foo(state = 'bar', action) {
    switch (action.type) {
      case SOME_CONSTANT:
        return action.foo;

      default:
        return state;
    }
  }
};

export default { actions, reducers };
```

I'm not entirely sure how that could be done automatically, because the `import { SOME_CONSTANT }` statement would (or should) always be what `someProvider` is exporting.  The author of `someProvider` would still be responsible for properly namespacing the action types.

However (and thank you for getting me to think about this some more!) I have been considering getting rid of the `combineProviders` functionality and replacing it with a better, designated way to listen for specific action types from other providers.  This would lead to a couple improvements!  First, the action types could be automatically namespaced since they wouldn't rely on an `import` statement.  Second, the providers' stores would remain separate, which would make re-renders even more efficient.

I think the ability to listen to specific actions from other providers is the route we'll go with this.  :)

**Comment by FredyC** [comment]
>> So essentially in case when there will be just one store

> Do you have an example where this would happen? With the providers paradigm, keeping everything in one store would be indicative of a design flaw, I think. It's best to keep things separate, not only for logical concerns and reusability, but for performance as well.

Isn't that like [first principle of the Redux](http://redux.js.org/docs/introduction/ThreePrinciples.html)? It's hard for me to imagine how would that work for example with `redux-devtools` if there would be multiple stores.

> I'm not entirely sure how that could be done automatically, because the import { SOME_CONSTANT } statement would (or should) always be what someProvider is exporting. The author of someProvider would still be responsible for properly namespacing the action types.

I meant it more like having API that can be reused by provider authors to have unified way of namespacing.

I definitely need to dive more deeply into this as it's hard to talk about something I don't have direct experience with yet :) I am glad I gave you something to think about. Listening for actions from other providers sounds really interesting.

**Comment by FredyC** [comment]
Perhaps this could a way to go around action types namespacing. I found it just recently, so no real experience with it, but looks like interesting way without increasing bloat: https://github.com/grigory-leonenko/redux-easy-actions

**Comment by timbur** [comment]
To be honest, the first principle of Redux is pretty silly.

It's a bad idea to design any large, complex application that way, where everything is intertwined.  The app as a whole becomes more difficult to reason about because concerns aren't separate enough and you have to consider hundreds if not thousands of switch statements and actions.  Performance will suffer as well (unless you put a bunch of effort into it, which shouldn't be necessary otherwise).

The best way to build large, complex apps (well, apps of any size really) is to essentially create a handful of separate, smaller, simpler apps that can work on their own, and then put everything together to form the larger application.  Providers (and everything that comes with them - i.e., separate stores, etc.) makes this extremely easy!

**Comment by FredyC** [comment]
I wouldn't really consider single Redux store as _intertwined_. Essentially everything can be pretty much separate in it's own folder/module and only common place is final reducer combined from those small ones and then passed to the store. This is how kinda how imagined at first this approach of yours would work. Did not really thought about going that far as separating each stores.

What I can say from my practice on the current project, that things are not always that nice and ideal to have everything separate. It is really handy to allow reducer to process the action that wasn't originally meant for it. For example I have a module that controls fullscreen behavior. When this is changed based on user interaction, I can dispatch single action to write new state and some other reducers can update their state based on that, eg. updating size of screen in the store, hiding currently displayed tooltip, etc...

Not sure what do you mean for a performance issue. Yes it might be a problem when cloning plain objects of a whole store on every action, but with eg. ImmutableJS where old data are essentially shared, I don't see a problem there either.

**Comment by timbur** [comment]
It's intertwined because every action results in calling every single reducer, which isn't terrible in-and-of itself, but it's not good when you want to keep your concerns separated because it leads down a road where you'll find yourself hacking things together in a way that no longer keeps your concerns separated, and next thing you know, you're in technical debt.

And performance is an issue because of all of the `shouldComponentUpdate` checks which typically process quite a few comparisons and can be difficult to optimize for thousands of nodes, especially when you can't cache `propTypes` to `reducers` like you can with `providers`.

**Comment by langpavel** [comment]
Another example: Imagine user behavior analysis component. You will listen to all actions (only few actually blacklisted), then at some point you get collected log and wish to replay it to see actual UI state. This would be pretty nice component but I think it is impossible if you separate stores.

Creating namespaces (or I actually mean subnamespaces) on only one store is difficult to generalize, consider array of components of same type.. 

BTW `@provide` decorator is awesome!

**Comment by timbur** [comment]
@langpavel Thanks!

You can replicate the UI state with multiple stores just as easily as with a single store.  The keyword here is "replicate", as it's a critical piece of the puzzle.  I think the lack of replication in most folks' arsenals is the main reason people seem to be having issues with building real-world apps.  I'll describe its usefulness in more detail after I've completed some other things.  :)

Also, I'm not entirely sure what you're referring to about namespaces, but if it is what I think it is, you can instantiate multiple components of the same type using their own instantiated providers of the same type by simply passing another `providers` prop like so:
```js
import Bar from './Bar';
import provideSomething from '../providers/something';

class Foo extends Component {
  render() {
    const providers = {
      ...this.contextProviders,  // we can keep using the same context for other providers
     something: provideSomething()  // and then instantiate a new `something` provider
    };

    return (
      <Bar providers={providers} />
    );
  }
}
```

**Comment by langpavel** [comment]
Oh I see, I will look at all in more depth and try to write something :-) Thanks for quick response. 

Do you suggest me something I can use to abstract out API layer? I wish to wrap out REST and websocket

**Comment by timbur** [comment]
> Do you suggest me something I can use to abstract out API layer? I wish to wrap out REST and websocket

Replicators are part of that, but it depends on your exact requirements.  :)  Does the REST API and/or sockets already exist and do you have full control over them?

**Comment by langpavel** [comment]
Ok, thanks, I must dive into replicators first. I wish to write generic tool for postgres from zero. 
May be table list/editing control. It's complex enough but focused.

**Comment by FredyC** [comment]
> It's intertwined because every action results in calling every single reducer, which isn't terrible in-and-of itself, but it's not good when you want to keep your concerns separated because it leads down a road where you'll find yourself hacking things together in a way that no longer keeps your concerns separated, and next thing you know, you're in technical debt.

Ok I can see what you mean @timbur. Yes it might be indeed somewhat confusing when other part of state are changing based on a single action, but other way around seems awfully verbose. I mean in my case when I want to update state of the fullscreen, hide tooltip and resize window screen ... I would need to dispatch 3 different actions or more precisely call 3 different functions provided to me.  So essentially the component becomes more smart about what exactly should happen. I guess that separation is better.

Well we are way off the topic here. I will first get my hands on this before going further in my conclusions. Thank you for all you replies. If you don't mind keep this open for a bit in case I really run into some issue later.

**Comment by timbur** [comment]
Yeah no problem!  I'll keep it open.  I think I'll actually implement the ability to listen to specific actions from other providers tomorrow, after I've thought about it some more.

Also, @langpavel there are a couple of things I may need to add to `redux-replicate`, which I'll also try to get to tomorrow.

**Comment by langpavel** [comment]
Ok, thanks, I'll look at it tomorrow too.

**Comment by timbur** [comment]
Quick update:  All of this is still in the works.  Making decisions on how exactly everything should work is the tough part.  Regarding replication, I can't decide if I want to incorporate something GraphQL-like into it or not.  I feel like it should be possible to specify the entire data structure/dependencies at once and then pass the relevant states from Redux to the replicators.  So suppose you're using multiple providers (and thus multiple contexts), where for example, you want to replicate some user's blog entries to a database.  You'd just need to specify that the entry state is dependent on the user state, and then `redux-replicate` will extract the relevant data from multiple stores to be passed to the database replicator.  For a simple key-value store, it might look something like this:
```js
replicate(
  'entries', fsReplicator((storeKey, state, action) => {
    const { userId, entries, selectedEntryKey } = state;
    const userEntryKey = `userId=${userId}&entryKey=${selectedEntryKey}`;

    return {
      [userEntryKey]: entries && entries.get(selectedEntryKey)
    };
  })
));
```

This actually already works.  It will initialize the stores' states, and keep the database up to date upon each change.  The problem to be solved next though is... How will queries work?  I suppose a way to use GraphQL-like templates might be the best route, since most people are familiar with it.  Just need to brainstorm some more and map out all of the requirements... I may use this particular issue as a place for that lol.

**Comment by timbur** [comment]
Another quick update: I had to take roughly a month away from all this, but as of a week or so ago I've gotten back into it and the refactoring of everything is now complete.  I'm really liking the new API.  It makes everything incredibly simple and declarative.  Now all that's left is updating all of the other repos (I think at least 9 total), examples, readmes, etc., to reflect the changes.  There's also one other thing (queries) I'm considering integrating into the core of the replication system.  Not sure how difficult that might be.  Probably not too difficult!  Hopefully by this weekend the new versions for everything will be published.  Depends on if I run into any unexpected problems.  :)

**Comment by timbur** [comment]
Welp, I did run into quite a few unexpected problems.  It took forever to get to this point but here's another update: https://github.com/loggur/react-redux-provide/issues/25#issuecomment-223730033

I'm pretty happy with how everything works now.  These changes aren't yet published, as I need to do further testing to be certain everything is working 100%.

**Comment by timbur** [comment]
README is up to date and all of the concerns within this issue should now have a solution!  Please let me know if there are any questions.
