### ISSUE TITLE
Running logic within the provider based on external data source?

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#16]
I have an old module written with Backbone which calculates some stuff periodically. There are some events when data changes. I need to glue this together with React components.

I can create provider with proper actions and reducers, but I don't like idea of creating a component that would essentially just dispatch update actions based on events. Sounds dirty to me.

However I suppose that I cannot really access dispatch within provider, can I?

**Comment by timbur** [comment]
You can access dispatch within a provider by using a store enhancer or by using the thunk middleware.  However, the recommended way to keep a provider's state in sync with external data sources is to create a replicator and use [`redux-replicate`](https://github.com/loggur/redux-replicate), which is really just a fancy store enhancer that handles the state initialization and updates for you.

I had to take a few weeks off from working on all of this, but I'm able to get back into it now.  I'm currently in the middle of making some pretty good changes, many of which were inspired by our discussion over in #11.  Hopefully by this weekend I'll have everything published.  The readmes and examples are getting a makeover as well, so those should hopefully be much better too!

**Comment by timbur** [comment]
Also, if you can show me an example of what exactly you need to do, I should be able to better help you solve the problem.  :)

**Comment by FredyC** [comment]
Yes, I been looking over examples and spotted the enhancer. Sounds like a good way to go.

```
function createEnhancer(attributes) {
	return (next) => (reducer, initialState) => {
		const store = next(reducer, initialState);
		attributes.on('change', (attributeModel, changedProperty, newValue) => {
			store.dispatch(
				actions.update(attributeModel.get('id'), changedProperty, newValue)
			);
		});
		return store;
	};
}
```

Haven't tried it yet as I had to side track to something else, but looks like a good way to go.

**Comment by Anifacted** [comment]
@timbur, I have a question related to this:
I am looking to use replicators for managing state synchronisation between client/backend. I like the concept of not having actions know about any external API, and leave that responsibility to a "plug-and-play" replicator instead.

I can see how replicators are awesome for event-based, real-time syncing or in situations with localStorage, where you just replicate JSON or with the example from `redux-replicate` docs, where you just listen on updates via some socket connection.

But how would you solve listening for incoming data, when the API is completely pull-based?

**Example:**

Let's suppose I've set up a "notifications" provider. I want to mark a notification as "read".
Now, in my React component I have a button "Mark as read" which when clicked, will trigger the following flow:

**1:** Notification provider's action `markAsRead(notificationId)` is fired.
**2:** Notification reducer calculates state. e.g.:
```javascript
case MARK_NOTIFICATION_AS_READ:
  return {
    ...state,
    ...[action.notificationId]: {
      ...state[action.notificationId],
      read: true
  }
```
**3:** Notification replicator fires **onStateChange**, which in turn fires the HTTP request. e.g.:
```javascript
onStateChange(key, state, nextState, action) {
  // Does this switch even make sense? Feels like an odd approach.
  switch(action.type) {
    case MARK_NOTIFICATION_AS_READ:
       clientApi.post(`notifications/${action.notificationId}`, { read: true })
    break
  }
}
```
This is where it falls apart from me. How do I follow up on that async request? What if it fails? How do I "roll back" the state change. I don't have access to `store.dispatch` from within `onStateChange`.

What am I missing? Should replicators even be used for this scenario, or should the API calls happen in the actions instead as otherwise done in Flux?

**Comment by timbur** [comment]
@Anifacted I'll pass the `store` as the 5th argument in a patch.  That should solve your problem right?  Earlier versions of `redux-replicate` included the store but I was a dummy and forgot to include it with the latest version lol.

That said, the reason I forgot is actually because [`provide-page`](https://github.com/loggur/provide-page) includes a `Form` component which makes it easy to trigger actions on both the client and server, while also allowing your app to function for users with JavaScript disabled.  So when using `provide-page` (and its `Form` component to trigger actions), you won't need to create a replicator for client-server communication.  Any replicator(s) will typically be used only for storing/retrieving data to/from your database and/or for real-time functionality via sockets.

But yeah it should definitely be possible to have custom client-server communication via replicators (especially for cases where you want to integrate with other services), so including the `store` as a 5th argument should solve any problems there.

**Comment by timbur** [comment]
Also, sorry for the delay.  I've been a bit under the weather lately so I haven't been running on all cylinders lol.  I am almost finished working out the kinks with everything and updating the boilerplates and examples.  And at which point I'll try to update everyone on best practices for all of this which should hopefully help out quite a bit.  I think building apps of any size and scale is about to get a lot easier.  😀

**Comment by Anifacted** [comment]
@timbur That makes things a lot easier, thanks! I figured that there was probably some deeper reasoning behind not exposing the store in this part of the lifecycle, and that it might be related to some conceptual ideal, hence I thought I was missing something fundamental about how replicators are supposed to work.

I am definitely not pro adding features in an ad-hoc manner whenever a specific need arises (which may be edge-casey), but if this does not break with any ideal pattern, then good thing it was caught 👍 

And thank you for reacting quickly. No need to apologise for anything - I respect your efforts highly! Feel better soon! :)

**Comment by timbur** [comment]
Alrighty!  All of the replication stuff is basically finished now and the README is up to date and should hopefully contain all of the info needed to really integrate providers with external data sources.  Please let me know if you have any questions!
