### ISSUE TITLE
Could that be used to provide filtering over a list

### ISSUE THREAD

**Issue by pke** [loggur/react-redux-provide#2]
After initial skepticism I begin to like the idea of provide.
I'd have the need to filter a list of different typed items by there type, specific properties and keywords.
Would that be a use case for a `filter-provider` that contains/shares a list of items and the filter definitions applied to them?

**Comment by timbur** [comment]
:)

You may want to check out [`react-redux-provide-list`](https://github.com/loggur/react-redux-provide-list) for a way to instantiate lists to be shared across multiple components.  It provides predictable methods (basically an `Array`'s methods) to components that you can use to manipulate said list(s).

So if you want to filter some list, you'd start by initializing the list when mounting the app:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import { assignProviders } from 'react-redux-provide';
import provideList from 'react-redux-provide-list';
import Lebowski from './components/Lebowski';

const list = provideList();

const initialState = {
  list: [
    { theDude: 'abides' }
  ]
};

assignProviders(initialState, { list }, { Lebowski });

// Alternatively, what I do in larger apps is create ./components/index and ./providers/index, then...
// import providers from './providers/index';
// import components from './components/index';
// ...which lends to better organization and allows for simply assigning providers like this...
// assignProviders(initialState, providers, components);
// ...as it automatically assigns providers as necessary.

ReactDOM.render(<Lebowski/>, document.getElementById('root'));
```

And then in your component(s) you'd specify that you want the `filterList` method for said list:
```js
import React, { Component, PropTypes } from 'react';
import provide from 'react-redux-provide';

@provide({
  filterList: PropTypes.func.isRequired
})
export default class Lebowski extends Component {
  // You can then call `this.props.filterList` in this component,
  // which works the same as `Array.prototype.filter` and will provide
  // a new filtered list (and/or item(s)) to any other components requiring it.
  render() {
    return (
      <div>etc.</div>
    );
  }
}
```

You can also predictably change the list, item, and method names like so when instantiating your list:
```js
const lebowskiList = provideList('lebowski', 'bigItem', 'bigIndex');

const initialState = {
  lebowskiList: [
    { theDude: 'abides' }
  ]
};

assignProviders(initialState, { lebowskiList }, { Lebowski });
```

You'd then use `filterLewboskiList` where applicable instead of just `filterList`, which in turn allows you to quickly provide multiple lists and methods to your components.  Hopefully [`react-redux-provide-list`](https://github.com/loggur/react-redux-provide-list) has all any remaining info you need there.  :)

There's also [`react-redux-provide-map`](https://github.com/loggur/react-redux-provide-map) for ES6 `Map` instances.

And there's also [`redux-replicate`](https://github.com/loggur/redux-replicate) which is designed for very easily dynamically initializing and persisting your states through replication.

**Comment by timbur** [comment]
Oh, I forgot to add... You can also easily "extend" providers if you want a more implicit filtering method.  See https://github.com/loggur/branches/blob/refactor/providers/projectMap.js for an example where we wrap the basic `Map` provider with some custom actions and reducers.  There's probably a more elegant solution for this but I haven't found it yet.  :)

**Comment by pke** [comment]
Thanks I'll look over it later. Just wanted to say that I abide your style of sample code. Mentioning my buddy The Dude ;)

**Comment by timbur** [comment]
Just in case you tried the last example I gave you, I made an error.

This:
```js
const lebowskiList = provideList('lebowski', 'bigItem', 'bigIndex');
```

Should be this:
```js
const lebowskiList = provideList('lebowskiList', 'bigItem', 'bigIndex');
```
