### ISSUE TITLE
Add the ability to create custom action objects

### ISSUE THREAD

**Issue by psachs21** [loggur/react-redux-provide#22]
So I'm trying to create a provider wrapped around React Redux Router and there is just one thing that I'm having trouble figuring out. I'd like to group all the actions related to routing under an object called ```history``` so if any component defines the prop ```history``` it will actually be populated with all the actions that can be performed on the history object.

ex:

```
const navLink = ({ history }) => {
  ...
  history.push(path)
  ...
};
```
 I initially tried to use the mapDispatch prop on a pre-6 version but found out we only look for keys on actions/reducers/merge. So i tried moving the actions into the merge. However, this doesn't work because I need access to the dispatch function in order to bind the methods. Any idea about how I could resolve this?

I'm going to try to upgrade to 6+ and see I can figure it out there.

**Comment by timbur** [comment]
You can use a router with providers but I've found it to make things more complicated because it forces you to keep track of one more paradigm.  The recommended way to handle routing is to have a provider with reducers which return values based on the current URL.

If you check out [`provide-page`](https://github.com/loggur/provide-page), you'll see that it [includes an enhancer](https://github.com/loggur/provide-page/blob/master/src/index.js#L282) that dispatches an action whenever the URL changes.  The action can then of course be used within reducers to update the state of your application.  The example blog application, [`bloggur`](https://github.com/loggur/bloggur), is still using v5, but I'll try to get it updated to v6 ASAP.  To give you an idea (super condensed version) for what it would look like with v6:

```js
// src/providers/entries.js

import providePage from 'provide-page';
import { PUSH_WINDOW_PATH, REPLACE_WINDOW_PATH } from 'provide-page';

const actions = {
  ...providePage.actions,

  whateverActionYouNeed() {
    return { type: SOME_ACTION };
  }
};

const reducers = {
  ...providePage.reducers,

  editingEntry(state = false, action) {
    switch (action.type) {
      // the page provider's enhancer dispatches this action with the split window path
      case PUSH_WINDOW_PATH:
      case REPLACE_WINDOW_PATH:
        return action.windowPathSplit[1] === 'edit';

      default:
        return state;
    }
  }
};

const merge = providePage.merge;

const enhancer = providePage.enhancer;

export default { actions, reducers, merge, enhancer };
```

And then within your components all you need to do is:
```js
import React, { Component, PropTypes } from 'react';
import { EntryEditor, EntryContents } from './index';

export default class Entry extends Component {
  static propTypes = {
    editingEntry: PropTypes.bool.isRequired
  };

  render() {
    const { editingEntry } = this.props;

    switch (true) {
      case editingEntry:
        return (
          <EntryEditor/>
        );

      default:
        return (
          <EntryContents/>
        );
    }
  }
}
```

What I really like about this approach is the simplicity of it combined with the fact that you have full control over any component renders based on URL state.  It allows you to do things very predictably and straightforwardly like... if you know you have a static header, you can put that near the top of your component tree and keep your routing logic below it.

I have to step out for a few hours but let me know if you have any questions.  If you're able to share your current routing situation, I'd be glad to help with fitting it into the providers paradigm.

**Comment by psachs21** [comment]
I've looked at provide page and I found that I prefer the very declarative routing scheme provided by react-router. Both, I think, are legitimate routing mechanisms. I'm mostly doing this this as a chance to dig into what makes providers work. I'm just having an issue getting my enhancer to properly sync the store with the browser history:

```
const enhancer = next => (reducer, initialState, enhancer) => {
  const store = next(reducer, initialState, enhancer);

  const syncedHistory = syncHistoryWithStore(browserHistory, store, {
    selectLocationState: (state) => state.router.routing
  });

  store.dispatch({
    type: 'SYSTEM_SET_HISTORY',
    payload: syncedHistory
  });

  return store;
};
```

I also have a basic reducer saving the syncedHistory to the state object. I then initialize the router like so:

```
const routes = ({ router }) => {
  return <Router history={router.history}>
    <Route path='/' component={App}>
      ...
    </Route>
  </Router>;
};
```

However, react router doesn't seem to actually sync histories. When I issue redux actions to push routes, the url changes but react router doesn't respond.

**Comment by psachs21** [comment]
Hmm, I think i know why this wouldn't work. router history can't (or shouldn't) be modified because it should be immutable (as a part of the store).

**Comment by timbur** [comment]
To keep your states in sync with the history, you just need to listen for the [`popstate` event](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_popstate_event) (or whatever `browserHistory`'s equivalent is, assuming there's some polyfill) and dispatch the action whenever it changes:
```js
const enhancer = next => (reducer, initialState, enhancer) => {
  const store = next(reducer, initialState, enhancer);

  const syncedHistory = syncHistoryWithStore(browserHistory, store, {
    selectLocationState: (state) => state.router.routing
  });

  const setHistory = () => store.dispatch({
    type: 'SYSTEM_SET_HISTORY',
    payload: syncedHistory
  });

  setHistory();

  browserHistory.on('change', setHistory);

  return store;
};
```

Then you can have a `router` reducer or a `history` reducer or whatever you need, which will return a new router/history object:
```js
const reducers = {
  history(state, action) {
    switch (action.type) {
      case SYSTEM_SET_HISTORY:
        return { ...action.payload };

      default:
        return state;
    }
  }
};
```

And then in your routes component:
```js
const routes = ({ history }) => {
  return <Router history={history}>
    <Route path='/' component={App}>
      ...
    </Route>
  </Router>;
};

routes.propTypes = {
  history: PropTypes.object.isRequired
};
```

This code almost certainly won't work for you since I don't know enough about your particular setup, but it should hopefully point you in the right direction.

**Comment by psachs21** [comment]
I'll take a look and see how it goes. I'll report back with success/failure. Thanks for your prompt replies.

**Comment by timbur** [comment]
Sure, no problem.

I just saw that [`react-router-redux`](https://github.com/reactjs/react-router-redux) has `history.listen`.  I'll update my previous comment to reflect that.  Again, no idea if the example code I'm giving you will work but it should be close!  :)

**Comment by psachs21** [comment]
So, I was being dumb. Turns out if I just have this as a enhancer:

```
const enhancer = next => (reducer, initialState, enhancer) => {
  const store = next(reducer, initialState, enhancer);

  syncHistoryWithStore(browserHistory, store, {
    selectLocationState: (state) => state.router.routing
  });

  return store;
};
```
 
I can use browserHistory by ``` import { browserHistory } from 'react-router'``` and it will return the modified browser. I don't know how many times i read the word 'singleton' and didn't connect that. Anyways, that's fine now. 

Back to my original question. If I want to namespace my actions, regardless of routing, is there a way I could do that? I'd like for my components to to look something like this:

```
const navLink = ({ actions }) => {
  ...
  actions.push(path);
  ...
  actions.pop(...);
  ...
};
```

Where actions is really just a hash of bound action creators. I want to do this because the actions on redux-react-router are so simple (push, pop, go, goBack, etc) that I want to be explicit about where they come from. I think this might be generally useful to allow namespacing of anything but in my case, I just want actions.

**Comment by timbur** [comment]
There are a few different ways to differentiate (namespace) props of the same key for different components, but if `actions` is unique (i.e., only the router uses that), you might as well provide it to components via a reducer.  Providing actions via some reducer probably sounds strange at first but I personally see nothing wrong with it.  :)

Other than that, if you do actually need to use some `actions` prop from multiple sources, I would need to know exactly what you might be able to use to differentiate/namespace them before I can make the best recommendation.  I will say that with v6 you can create dynamic (namespaced) providers by including a `key` function with the provider object, where the function should accept some relevant component instance and return the key based on the components props, context, or whatever you need.  Matching keys will of course use the same provider instance (and thus, store).  This is especially useful for things like managing the state of different users:
```js
providers.user.key = componentInstance => `userId=${componentInstance.props.userId}`;
```

Since there does seem to be a demand for using `react-router` with providers, I think I will create something to officially support it.

**Comment by psachs21** [comment]
With regards to creating a react-router wrapper with providers, that would be really awesome. I've got it working in an example project you can find [here](https://github.com/influitive/reforge-boilerplate/tree/development/examples/counters). There is a router provider that covers the basics. I think we'd need to make it into a factory (taking the desired history object) but it works. Although I have found a weird issue where I have to wrap the routes class with provide even though it doesn't actually have any provided props.

Regarding the issue with binding actions to a reducer, how would you do that? Could you provide an example provider that does that? I know I need access to the store.dispatch method in order to bind properly.

**Comment by timbur** [comment]
Thanks for the example project.  That should definitely help me out.  :+1: 

> Although I have found a weird issue where I have to wrap the routes class with provide even though it doesn't actually have any provided props.
With v6 you should just be able to `import 'react-redux-provide/lib/install'` before anything else React-related and it will enable providers for all components and allow them to be completely independent/decoupled from `react-redux-provide`.  Hopefully `react-router` isn't doing anything strange that might create conflicts when using the `install` method.

And to bind actions to a reducer, the quickest/easiest way would probably be to dispatch it within your enhancer.  Something like this:
```js
const SET_ACTIONS = 'SET_ACTIONS';

const reducers = {
  actions(state, action) {
    switch (action.type) {
      case SET_ACTIONS:
        return action.actions;

      default:
        return state;
    }
  }
};

const enhancer = next => (reducer, initialState, enhancer) => {
  const store = next(reducer, initialState, enhancer);
  const { actions } = browserHistory;

  store.dispatch({ type: SET_ACTIONS, actions });

  return store;
};
```

I'm not sure where your `actions` object is coming from exactly, and since the providers paradigm is designed so that you're declaring only the action(s) that each component actually needs, this isn't the most elegant solution.  But it will work.  :smile: 

I personally prefer the more explicit approach of having each action key itself namespaced - e.g., `pushPath` instead of `actions.push` - that way it's immediately obvious what exactly a component is meant to do from a glance at its `propTypes`.  It also helps to keep components small and simple (concerns separated) so that one component isn't attempting to do many different things at once.  Do whatever works best for you though!  :smile:

**Comment by timbur** [comment]
Forgot to add:  If the `browserHistory` object is a singleton and you're already importing that into your component modules, you should probably just get the `actions` object from that instead of from the provider/props.

**Comment by timbur** [comment]
Hmmm... I'll also add that the providers paradigm is designed to keep things as simple and predictable as possible by following a particular abstracted design pattern, so it's easy to run into issues when trying to combine it with the lower level design patterns required by vanilla Redux and `react-redux`'s `connect`.  You can most definitely achieve the functionality you want (and more cleanly) with a provider designed specifically for `react-router`, rather than attempting to fit `react-router-redux` into a provider.  Are you pressed for time on this?  I should have time to create an official router provider within the next week, maybe even this weekend.

**Comment by psachs21** [comment]
No, not pressed at all. Just enjoying digging in. In regards to using react-router-redux, it seems to make sense to be able to hook it in because they already solved the integration of redux and react router, we don't want to be solving things that were already solved.

**Comment by SeeThruHead** [comment]
To add, I think access to the underlying apis of redux and react-redux is a really important thing to have. That way we can use the redux-provide abstraction when it fits, and extend it with paradigms we already know from vanilla redux. That leads me to ask that react-redux's connect be exposed through merge at some point. Passing down bound action creators via state just seems wrong. 

Hopefully you agree :smiley:

**Comment by timbur** [comment]
> Passing down bound action creators via state just seems wrong.

Agreed!  :grin: 

I think the main problem here is trying to fit certain structures/patterns from `react-router` and/or `react-router-redux` into the provider pattern.  It can definitely fit but you'll need to be a bit more accepting of how props are named.

Providers are designed to help keep things simple as possible while being explicit (and efficient!) so you don't inadvertently make things more difficult for yourself (or for others) later down the road.

For example, when I began building things using providers, I had the same inclination where I wanted a single object I could use, similar to what you're asking for here with the ability to call `actions.push` and `actions.pop`... but over time I realized that it is actually much easier and a much better design to always keep things at a single level and simply use props like `pushWindowPath` and `popWindowPath`.  Sure, the lack of camel-case with `actions.push` might be a little more visually appealing, and at first, an `actions` object might feel a little better since we tend to think of things as objects, but is it really better?

Imagine someone looking at the component for the first time.  The intent/usage of `pushWindowPath` (or even just `pushPath`, or maybe `pushURL`) is immediately obvious, whereas with something like `actions.push`, it isn't immediately obvious unless you're already familiar with the codebase.  And so anyone unfamiliar would have to either read the surrounding code and gain some understanding of the context behind the call to `actions.push`, or they'd have to trace the `actions` object to the source and figure out what its `push` method is designed to do exactly.  Now, for this particular case, someone could probably quickly figure out that `actions.push` is meant for routing/history, but it won't always be that quick and easy for other nested designs.  It's much easier to only ever have to consider things at one level.  Plus, even if there is some confusion about what `pushWindowPath` is meant to do, a quick search using `grep` (or Sublime's text search or similar) will immediately lead you to the function definition since it's almost certainly guaranteed to be unique.  With something like `actions.push`, you'd probably need to do some tracing/debugging.

Beyond that, a flat provider API keeps everything predictable, reduces complexity, and helps prevent any inefficiencies.  Absolutely everything anyone should ever need for any size application can be represented at a single level as either the current state or an action creator to manipulate that state.  Anything more than that is a sign of an overly complex design, which often makes things more difficult in the future.

Anyway, that's my stance on it.  Does it make sense?

**Comment by psachs21** [comment]
I think it does make sense. I think we can work with the flat structure as long as we prepend the action keys, which can be done when registering the producer.

**Comment by timbur** [comment]
I just published [`provide-router`](https://github.com/loggur/provide-router).  v6.0 of `react-redux-provide` seems to work much better with `react-router` than v5 did.  I'm really liking how it turned out.  I like it so much that I will definitely convert all of the relevant examples/boilerplate to use the router provider within the next 24 hours.

Thanks again for your router example!  It helped me quickly knock out `provide-router`.  And thanks for pushing me in the right direction!

**Comment by psachs21** [comment]
It looks good and will be really helpful once we really start digging in. Thanks a bunch!
