### ISSUE TITLE
Caching based on DisplayName?

### ISSUE THREAD

**Issue by psachs21** [loggur/react-redux-provide#28]
I recently ran into a very strange issue that I'm having problems explaining and simplifying a reproducible example.

So here's what happens:

I have a component library that has a component with the display name 'Message' (let's call this one LibMessage). I have my own component called with the same displayName (lets call it OriginalMessage). If i include LibMessage in the component tree, the next render pass of OriginalMessage, the LibMessage render method is called instead of the OriginalMessage.render method. If I change my displayName to be anything but 'Message' it works fine. 

I've been using both react-redux-provide and recompose, so I'm not 100% sure where this is coming from but given the relative simplicity of recompose, I figured provide was probably a good bet.

Any ideas would help.

**Comment by timbur** [comment]
Is this an issue in production?  In development, all of the component instances are cached by their [`displayName`](https://github.com/loggur/react-redux-provide/blob/a266d1f4612155987e71b2c62f2148403bf01f30/src/provide.js#L23) so that they can be [hot reloaded](https://github.com/loggur/react-redux-provide/blob/a266d1f4612155987e71b2c62f2148403bf01f30/src/provide.js#L468-L472) (which involves reinitializing/reassigning the providers if the component's `propTypes` have changed) and so that [providers may also be hot reloaded](https://github.com/loggur/react-redux-provide/blob/a266d1f4612155987e71b2c62f2148403bf01f30/src/provide.js#L508-L522).

Does the problem occur on all renders, or just when hot reloading?

I wonder if using a randomized key instead of the `displayName` might solve the issue.  That would depend on how the hot reloading updates the `ComponentClass`, I guess.  The randomized key would need to remain on that object so that we'd know which instances to reinitialize.

**Comment by timbur** [comment]
I'll try a few things real quick and maybe push a patch for you to test.

**Comment by psachs21** [comment]
Actually, just in development. It does occurs somewhat sporadically, sometimes one component loads and the other fails or vice versa. Probably hot reloading. I'll disable hot reloading to confirm.

**Comment by psachs21** [comment]
Confirmed, it works fine without hot reloading.

**Comment by timbur** [comment]
@psachs21 Can you confirm that the problem is fixed?  I fixed a couple of other bugs with hot reloading while I was at it.

**Comment by timbur** [comment]
Good timing btw lol.  Ensuring hot reloading was working 100% was at the very top of my todo list today.

**Comment by psachs21** [comment]
Awesome. I'll give it a shot.

**Comment by psachs21** [comment]
And it all seems to be working now. Thanks so much. This issue was driving me nuts.

**Comment by timbur** [comment]
I've just encountered another bug where hot reloading multiple times doesn't seem to work.  It only reloads once.  This might be specific to my setup but will definitely fix it asap.

**Comment by timbur** [comment]
Something must have changed with [`react-transform-hmr`](https://github.com/gaearon/react-transform-hmr) and/or its internals.  That is the only explanation.

At any rate, seems to be fixed.  @psachs21 Can you verify that everything is still working for you with `6.0.0-rc.30`?

**Comment by psachs21** [comment]
I'll give it a shot but i don't see rc.30 published on npm.

**Comment by timbur** [comment]
Oh whoops I think my connection crapped out when I tried publishing.  Trying again now.

**Comment by timbur** [comment]
Okay should be up now.

**Comment by psachs21** [comment]
Looks like it's also working fine.

**Comment by timbur** [comment]
Awesome, thanks!
