### ISSUE TITLE
Usage with Redux-router

### ISSUE THREAD

**Issue by FabienMotte** [loggur/react-redux-provide#3]
Hello !

I was asking me if is it possible to make it work with Redux-router ?
What value can I provide to React-redux `store` props ?
```javascript
import React           from 'react'
import ReactDOM        from 'react-dom'
import { Provider }    from 'react-redux'
import { ReduxRouter } from 'redux-router'
import { store }       from 'helpers'
import routes          from './routes'

ReactDOM.render((
  <Provider store={store()}>
    <ReduxRouter>
      {routes}
    </ReduxRouter>
  </Provider> ),
  document.getElementById('root'))
```

Currently, my `store` props is taking the returned object of this function :
```javascript
import { compose, createStore, combineReducers, applyMiddleware } from 'redux'
import { reduxReactRouter, routerStateReducer } from 'redux-router'
import thunk from 'redux-thunk'
import createHistory from './history'
import * as reducers from '../reducers'

const storeEnhancers = [
  reduxReactRouter({ createHistory })
]

const combinedCreateStore = compose(...storeEnhancers)(createStore)
const finalCreateStore = applyMiddleware(thunk)(combinedCreateStore)
const rootReducer = combineReducers({
  router: routerStateReducer,
  ...reducers
})

export default () => finalCreateStore(rootReducer)
```

Do I have to apply, for example, the `thunk` middleware to all of my providers ? Same with the `routerStateReducer` ?

Thanks for your answer !

**Comment by timbur** [comment]
Are you using `react-redux-provide` (this repo) at all?  It's designed to replace the usual `<Provider store={store()}>` on an individual component basis.  I haven't used it with a router yet, but that's on my todo list.  You may be better off asking this question over at the `redux-router` repo.

**Comment by FabienMotte** [comment]
Not using it because I can't figured out how to implement it with `redux-router`, but I like your approach, I will ask my question overthere, thanks !

**Comment by timbur** [comment]
I'll comment on this again when I've either implemented a router for this or made it work with an existing one.  :+1:

**Comment by yanivtal** [comment]
Hey, I have an API that would be really great for this. I think this project is amazing and with just a few tweaks, the combo of react-redux-provide + react-router can be really really good.

Currently, react-router route configurations look like this:
```
{
  path: route,
  component: MyComponent,
  childRoutes: []
}
```
This is the natural place to specify the provider - not as a whole extra step in a whole other file calling assignProviders.
Instead, the route configuration could look like this:
```
{
  path: route,
  component: MyComponent,
  provider: MyProvider,
  childRoutes: []
}
```
Perfect!

Now the last piece. Currently we need to put all the propTypes as a parameter to the @provide decorator. This is unfortunate because we can no longer write idiomatic React components. The React component is the cornerstone of a React application and asking users to change a central part of how every react component is declared is a big ask and tough sell.

Instead, we could just have a single @provide decorator on top of the function definition - with no parameters. The @provide decorator can look at context to see if the user is using react-router and if so can grab the Provider from the route config so that it can call assignProviders on the user's behalf. It also has a reference to the component from the same route config so it can access the static MyComponent.propTypes exactly the same way. Boom!

Now we can write idiomatic react components:
```
@provider
class MyComponent extends Component {
  static propTypes = {}
  render() {
  }
}
```

@timbur What do you think of that?

**Comment by timbur** [comment]
The original version of this package used `@provide` with no arguments, but I changed it to the way it is now to make it more obvious which props are meant to be provided via flux and to also allow for easier performance optimization, which I haven't yet gotten around to.  I think it would still be possible to have the same or similar optimizations without the arguments though (with a tiny bit more effort), and going back to the no-argument form would solve #1, so I will definitely consider that for the next version.

> Currently, react-router route configurations look like this:
> This is the natural place to specify the provider

Where is this exactly?  Is this in a config file for `react-route`?  The driving factor behind this package is to separate concerns while avoiding feature creep itself.

**Comment by timbur** [comment]
Forgot to add: Let me try a few things first with routing and server rendering and I think I can come up with an ideal solution for all of this.  :)  I'll keep you updated.

**Comment by yanivtal** [comment]
Cool. Right now the current approach adds too much boilerplate. We have a big team and one of the draws to using a library like this is to clean things up and make it more accessible. To me having react components just be react components is an important part.

Since most people writing large apps in React are using React Router, I think integration would go a long way. I understand wanting to do it as a separate add on though. From a conceptual standpoint, the router config is where you're "hooking things up". You're saying this view is going to use this component and these properties and I think this is exactly where you want to say "and wire it up with this provider".

Excited to see where this ends up!

**Comment by timbur** [comment]
Okay I see what you're saying now.  To clear things up a bit, `@provide` is designed to be used liberally everywhere (i.e., within nested components), so that you're not constantly having to pass props from parents to children and to their children and so on.  From your description it seems like you just want to use the provider(s) at the top level (routes) of the app and then pass things down from there?  I feel like there might be a misunderstanding here on both our parts.  :)

I'll create a blog app or something so you (and others) can have a better idea of how this package is intended to be used.  I'll try to make it as readable and understandable as possible.  Hopefully you'll like the design and see how easy it is to clean things up for large apps and make everything super accessible for teams!

**Comment by yanivtal** [comment]
Yeah, we try to limit how many smart components we have. Doing the top level components gets us 80% there but you're right that not every smart component will be at the top level so some assignProviders would be necessary.. Any reason assignProviders can't access YourComponent.propTypes so that we don't have to pass the prop types to the decorator?

**Comment by timbur** [comment]
> we try to limit how many smart components we have.

Nice.  That's the exact purpose of this library - i.e., make every component as "dumb" as possible so that all they're really doing is rendering your views as a function of the `props` passed to them.  :)

The `@provide` decorator wraps said "dumb" components with an auto-generated higher-order component designed specifically for the `props` each "dumb" component expects, and each of these auto-generated HOCs are responsible for updating the view of the component they're wrapped around, similar to `connect` in `react-redux`.  So you should never actually create any "smart" components.  All of the "smartness" comes from the providers which are just an assembly of `redux` `actions` and `reducers` and some other useful functionality - e.g., `merge`, `middleware`, `enhancer`, etc.

I think I will remove the arguments from `@provide` so that you only have to specify your `propTypes` within your "dumb" components as usual.  The code as it is should actually already work like that, so it'll probably be a 2-second "fix" and will solve #1 as well.

I need to wrap up something else real quick and then I'll try to put together a blog app (or something like that lol) as an example for how to design a moderately complex app using providers. :+1:

**Comment by jugimaster** [comment]
> auto-generated HOCs are responsible for updating the view of the component they're wrapped around

What does "updating the view" mean? For starters, I don't know that React component's "have a view".

I'm still getting to grips with Redux, and React-Redux _and_ React-Router, all at the same time, and together they're quite confusing. Especially when combined with all the Node-specific tools I _Do Not Want to touch_, but have to.

Anyhow, for example when I read this:
```
This small library allows you to:

    Build your entire app's view layer first - i.e., all your components become as "dumb" as possible.

    Decorate your components with @provide, which allows you to specify - as propTypes - exactly the data and actions said components need.

    When mounting your app, assign providers to your components as necessary.
```
I'm left none the wiser. Basically what I want to know is:

  - _**What**_ does it do?
  - _**How**_ does it do it?
  - _**Exactly**_ how do I use it?

Then there's some "List/Array"-thingy-library that's used in your examples, and I have no clue what that does either, and how and why.

**Comment by timbur** [comment]
To answer your first question @jugimaster, when I say "updating the view" I mean re-rendering the component.

As for the rest, I completely understand where you're coming from!  :+1:  I am planning on putting together a really in-depth example and tutorial to explain what I think is the absolute best design when building apps with React, both large and small.  It should help folks get started faster with building well-designed (flexible, composable/extendable, and efficient) apps and hopefully lead to a better understanding and who knows, maybe we'll realize some improvements/innovations along the way.  :)

**Comment by jugimaster** [comment]
Thanks for the response!

Well, even so, it's unclear what "_the_ view" is, and talking about views reminds me of MVC :)

I'm sure your tutorial will be great, but.. it seems to me that while good tutorials certainly help, they're basically just alleviating the underlying problem of way too much complexity in getting anything done in front-end development these days.

At some point, the front-end hive-mind decided that everything needed to be in "modules" even though JavaScript didn't even have them, and then all the module stuff ended up depending on Node because ```npm``` happened to be there already.

So now all front-end development depends on Node in one way or another, and that's just _really_ damn annoying to someone like me who's never written a Node app in his life.

I hope the hive-mind will ditch all the other module stuff once ES2015 modules are useable in the real world. That should remove quite a bit of the overhead.

**Comment by timbur** [comment]
I should have a pretty sweet setup for y'all to check out either by this weekend or the next (depending on how many issues I run into).  :sweat_smile:

**Comment by jugimaster** [comment]
Cool :)

**Comment by timbur** [comment]
Unsurprisingly, I ran into some issues, mainly with webpack.  I'm waiting to hear back about the last issue I've run into with hot reloading and then things should be good to go.

**Comment by jugimaster** [comment]
I for one am not surprised that a Node-based "modern front-end development" tool caused problems.. :P

**Comment by yanivtal** [comment]
Hey @timbur how are you going to be announcing the changes? I'm eager to dig in.

**Comment by timbur** [comment]
I'll describe the overall changes here and/or write an article about it and link to it here.  :)

Just a few things left to do:
[ ] - debug HMR
[ ] - post/put/delete API that works with and without JS enabled (might seem like feature creep at first glance but I think it's an integral part of the system and could be implemented fairly easily/simply)
[ ] - ensure everything works correctly in production
[ ] - update tests
[ ] - update readmes

**Comment by timbur** [comment]
Hey so the following post was originally intended as a response on an [/r/reactjs thread](https://www.reddit.com/r/reactjs/comments/43loav/shareable_react_components/), but it didn't fit so I'm pasting it here and linking to it.

Not entirely sure where to start so I'll just list everything I have so far.  As with all things, there are some tradeoffs but I think this design allows for maximum reuse, extendability, flexibility, maintainability, and understandability.  Designing, building, and testing web apps of any scale and complexity will be greatly simplified.  Some assumptions are made with the implementation, and it is a bit opinionated, but the implementation itself should also be very flexible such that anything can be swapped out for better modules in the future if they come along, as long as they follow the same paradigm.

Note: All of this is fully functional as of last week!  :)

* All you really need are 2 directories: `components` and `providers`.  A third `themes` directory is also recommended (we'll get to that below).

* Forget about containers and presentational components.  All your components should do is render the view of your app and trigger actions provided via `props`.  This results in a maximum separate of concerns which makes everything predictable and easy to reason about.  It also allows components from one app to be reused within other apps with no conflicts, no potential issues, and no unnecessary dependencies.
  
  All you need to do is decorate each component with `@provide` (from [`react-redux-provide`](https://github.com/loggur/react-redux-provide)), which wraps them with an auto-generated higher-order component (similar to `react-redux`'s `connect`) and allows each provider (see next bullet point) to be automatically assigned to components based on their `propTypes` when mounting the app.

* The `providers` directory contains everything for sharing data and controlling the app via flux.  Each provider should do one thing and do it well.  Right now providers are nothing more than simple objects with `actions`, `reducers`, an optional `merge` function, optional `middleware`(s), and optional `enhancer`(s) designed to work with `redux`.  As mentioned above, if something better happens to come along to internally support this paradigm, it should be feasible to easily swap things out.  I think `redux` will stand the test of time though.  :)
  
  Your providers should be as encapsulated/independent as possible, and you should typically try to keep your action types' constants contained within the provider, but there are some cases where it may be useful to share constants across multiple providers.  In other words, don't import constants into your components.
  
  To add to the concept of providers, if it hasn't occurred to you yet, this design also allows for providers to be packaged independently and you can even have provider "factories" (see [`react-redux-provide-list`](https://github.com/loggur/react-redux-provide-list) and see [`react-redux-provide-map`](https://github.com/loggur/react-redux-provide-map)).  And I think if this becomes widely adopted, we'll see a ton of really cool/useful stuff in the future where we're able to build apps that work perfectly on their own but can also be extremely quickly and easily integrate with one another.  So for instance, when trying to integrate another service into our apps, rather than tapping into RESTful API endpoints and/or taking days or weeks to decipher some documentation and integrate various libraries, all we would should ever have to do is `import provideGithub from 'provide-github'`, specify the necessary `propTypes` on our components, and boom... as `props`, we instantly have all the data and actions we need to use said service.  And it of course goes both ways.  If you want to expose an API for your app to other developers, simply package and distribute the same provider(s) you're already using in your own app.

* When mounting and rendering the app, since your components are all wrapped with the HOC created by `@provide`, all you have to do is pass a few `props` to your app: `providers`, optional `providedState`, and optional `combinedProviders`.  By default, each provider has its own store, but if you're sharing constants across multiple providers you'll need to specify that they should be combined via `combinedProviders` so that they can share a store and be aware of each other's actions.  It should also be possible to use multiple contexts and at any level within your app by simply specifying a different set of `providers`, `providedState`, and/or `combinedProviders` `props` wherever necessary.

* Now that we have the concepts of `components` and `providers` laid out, we can start doing some really nifty stuff.  :D  Replication is probably one of the most common/useful enhancements we can make.  [`react-redux-provide`](https://github.com/loggur/react-redux-provide) includes some useful utility methods, and so to add replication/persistence/whatever to our app, all we have to do when mounting is something like this:
  
  ```
  import { unshiftEnhancer } from 'react-redux-provide'`;
  import replicate from 'redux-replicate';
  import localforageReplicator from 'redux-replicate-localforage';
  import providers from './providers/index';
  
  const { theme } = providers;
  const themeReplicator = replicate(
    'theme', localforageReplicator({ themeName: true })
  );
  
  unshiftEnhancer({ theme }, themeReplicator);
  ```
  
  This particular example adds an enhancer to our `theme` provider to the beginning of its `enhancers` chain (which internally boils down to `compose(...enhancers)(createStore)`) and allows the state of the `theme` provider's `themeName` reducer to be replicated/persisted to our client-side storage and automatically restored upon loading the app.  You can do some awesome stuff really easily with replication like simply dropping in a socket replicator for real-time functionality... or instantly swapping out different databases without having to touch any other code within your app.  There's a bit more to it (e.g., separating client replication from server replication) but I'll revisit that topic another time.  :)

* I think theming deserves its own bullet point here.  When you design your app with theming in mind, it lends to even further separation of concerns (always good!).  With [`react-redux-provide-theme`](https://github.com/loggur/react-redux-provide-theme) (note: README on GitHub is outdated and doesn't reflect current functionality), you can provide themes as `classes`, `images`, `icons`, etc. to your components and they can be bundled using whatever you want, whether it's plain CSS, inline styles, [`css-modules`](https://github.com/css-modules/css-modules), [`jss`](https://github.com/jsstyles/jss), etc., etc., etc.  All it needs is a bundled CSS file and a bundled JS file containing the class names (as `classes`) at the very least.  The system behind it is designed with code-splitting in mind so that you're only loading the selected theme.  I'll elaborate more on that later.  :)

* Routing and server-side rendering!  I'm describing both of these things at once because they go together.  ;)  I think it's actually time to move beyond `react-router`.  It's a fantastic module but with the `providers` paradigm, there is no reason to use it.  There are of course a handful of different router attempts using `redux`, but they seem to fall short.  With [`react-redux-provide-page`](https://github.com/loggur/react-redux-provide-page) (note: also has a very outdated README at the time of this post), just use the provider as usual and keep your routing logic within your components' `render` methods.  There's really no need to try to put everything within your initial call to `render` when mounting the app (like we've been doing with `<Router>`), as that can get out of hand quickly for any large app.  All you need is `render(<App providers={providers} etc />)`.  If you need code-splitting, it should be implemented in the same way themes are split.  Again, I'll describe all that in more detail later.
  
  Now that we have the concept of routing confined to providers and whatever components rely on the routing state (current URL, document title, headers, status code (e.g., 404), meta info, js files, css files, etc.), we can easily and automatically handle server-side rendering.  [`react-redux-provide-page`](https://github.com/loggur/react-redux-provide-page) includes a few exports to make this insanely easy.  The main one is `createMiddleware` which creates middleware for `express` and ultimately generates the document HTML using a combination of React's `renderToString` and the states of your providers' stores.  (Remember that everything, including your app's title, headers, status, JS files, CSS files, etc. are all controlled via your providers!)  It also works asynchronously if your actions return a function (e.g., if you're using something like [`redux-thunk`](https://github.com/gaearon/redux-thunk))!
  
  And then there are 2 simple components exported: `Link` and `Form`.  The `Link` component is just a simple wrapper around `<a { ...props } />`, which intercepts the click event to prevent a full page reload when JavaScript is enabled and triggers the `pushWindowPath` `action` so the app can be updated accordingly; and of course if JS is disabled, since all your rendering logic depends on your page provider's store's state (using `request.originalUrl` on the server), it all renders exactly the same as it would if JS was enabled client-side.
  
  The `Form` component is super important but equally as simple.  Combined with `createMiddleware`, it allows all of your `actions` to be automatically triggered on the server, whether or not JS is enabled.  If it is enabled, it will trigger the action on the server via `XMLHttpRequest`.  This is another thing I'll describe in greater detail when I write the full article.  It's crazy simple to use!  It basically boils down to a `formId` prop combined with an `onSubmit` prop that accepts `formData` as a second argument.  :)


I ended up spending way more time on this post than I intended, but I think I've covered most of it.  I need to finish updating all the tests and readmes for everything and then I'll write a proper article describing every little detail, hopefully more organized and understandable than what I've written here.


Side note: I'm thinking of changing all my current packaged providers from `react-redux-provide-theme` (for example) to simply `provide-theme`.

**Comment by jugimaster** [comment]
Interesting, but confusing :)

**Comment by timbur** [comment]
Almost done updating the tests and readmes!  And then after I figure out some kind of fix (probably a plugin) for automatically hot reloading providers, I'll write a full article describing every detail more clearly (hopefully).  I think I may also put together a standalone module (or preset or something) that puts all of these different pieces into a single package with a super simple API so that folks don't have to concern themselves with all the boilerplate anymore.

**Comment by timbur** [comment]
Alright so the tests and readme updates are finished (although there are a few other minor readme updates I'd like to do but they can wait) and until I've finished debugging HMR and writing the article, you can check out [`provide-page`](https://github.com/loggur/provide-page) for routing and automatic server-side rendering (among some other pretty useful stuff) and [`bloggur`](https://github.com/loggur/bloggur) for a fully functional example.

**Comment by timbur** [comment]
Came up with a pretty decent solution to (mostly) automatically hot reloading providers.  :)

See the `reloadProviders` method under the [Usage](https://github.com/loggur/react-redux-provide#usage) and [Hot Reloading Providers Example](https://github.com/loggur/react-redux-provide#hot-reloading-providers-example) sections of the README.

I should be able to get started on the full writeup either later on today or some time tomorrow.

**Comment by jugimaster** [comment]
I'm not saying ```react-redux-provide``` is bad in any way, but how would you describe what it's used for?

**Comment by timbur** [comment]
Hopefully that will be clear after I've written about it.  I decided to take it easy over the weekend so I haven't written anything yet, but I will today.  :)

To answer your question though, I guess you could think of providers as an optimal way to share and manipulate data across any number of React components.  It's designed in a way that providers can be instantly swapped out (or upgraded) with other providers and everything will still work perfectly (if compatible of course).

And if this paradigm becomes widely adopted, it will *drastically* reduce the amount of time and effort it takes to integrate third party services into applications and/or make different applications work with each other.  It's as simple as components declaring, "I want this data and/or these functions to manipulate that data," and then when initializing the app, all you do is pass the providers to your top level component, which are automatically assigned to the components that need them.

**Comment by jugimaster** [comment]
Sounds good but I still have no clue :)

Let's take this "Explain it Like I'm Five" thing a bit further! :p

  - What exactly _is_ a Provider?
  - What does it do? (+How?)
  - When would you want to swap one for another?

**Comment by timbur** [comment]
Good questions.  I'll make sure to include my answers in the writeup.  ELY5 doesn't seem feasible without making things silly/confusing though lol.

* A provider is currently a combination of `redux` actions and reducers and it has its own store.  A store holds data and dispatches actions to the reducers.  The reducers control the data based on the actions.  You can also combine providers so that they use the same store and can listen for each others' actions.

* The `@provide` decorator wraps your React components in an auto-generated higher-order component, which is just a special component that controls the properties passed to the wrapped component.  Your providers are compared to the wrapped component, and if the wrapped component has `propTypes` matching some provider's actions or reducers, the provider will be assigned to the wrapped component.  By assigned I mean that the higher-order component subscribes to the provider's store and will update the properties of the wrapped component when the state of the store's data changes.

* There are two examples I can come up with off the top of my head where you might want to instantly swap one provider for another.

    * First example: Suppose you're building an app designed to use multiple different services which have the same or similar API (e.g., GitHub vs GitLab vs BitBucket, etc.), and the entire state of the app and how it functions depends on the selected service.  Without providers, you would likely have to implement custom logic across multiple components specific to each service, which can quickly become messy and especially time consuming if you want to add more services; it also makes all of your components dependent on specific services.  But when using providers, everything is decoupled and your concerns are separated, which allows for mixing and matching arbitrary components and services, as well as independent distribution.  All you need to do is have your components declare, "I want these properties and I want to be able to perform this action for the selected service."  And all providers need to do is ensure they're using a certain set of actions' keys and reducers' keys.

    * Second example: Suppose you're building a game with React where you want players to be able to use their own custom HUD (heads-up display, basically a dashboard for their status and other real-time info).  Without providers, the naive approach might be to use a single `HUD` object and pass it around throughout all of your components and use it wherever necessary, but similar to the first example, this can get pretty tedious and relatively time consuming, plus you would also likely need to implement custom rendering logic so that components know when to re-render.  But when using providers, you simply pass any compatible HUD provider to the top component and the only thing your components should concern themselves with is the relevant actions and reducers, as re-renders are handled automatically and efficiently.

**Comment by jugimaster** [comment]
Sounds like it could be pretty cool! :)

Let's see.. :p 

The ```@provide``` decorator wraps a component in a higher-order component, but that's something different from a "Provider"?

What does it mean to "compare providers to the wrapped component"?

Does a Provider's internal Store have a relationship to the global Redux Store?

**Comment by timbur** [comment]
`redux` technically doesn't have a global store, even most people seem to use it that way.  A provider's internal store is just an isolated instance of a `redux` store.  It's actually more efficient to have multiple stores, because it allows components to only re-render when the store(s) they're subscribed to have changed; whereas with a single (global) store, all components will determine whether or not they should update.  There's also some other things that can be done to make things even more efficient, but I'll get to that later on (not really important right now).

The `@provide` decorator allows the providers to be automatically assigned to the components.  You typically should never worry about its internal workings.  It just works.  :)

And to answer the other part of your question, it's probably best described through a few snippets.

Suppose you have a simple component `Foo`, which has a `classes` `propType` because we want our `Foo` component to be able to use different themes with namespaced (isolated) class names, which means its `className` is dynamic and should be a `prop`.
```js
import React, { Component, PropTypes } from 'react';
import provide from 'react-redux-provide';

@provide
export default class Foo extends Component {
  static propTypes = {
    classes: PropTypes.object.isRequired
  };

  render() {
    return (
      <div className={this.props.classes.Foo}>
        What a fooey component!
      </div>
    );
  }
}
```

And suppose this `Foo` component is used somewhere deep within your app.  Without providers, you would need to pass the `classes` prop repeatedly throughout all the components from the top component to your `Foo` component so that `Foo` could know its proper `className`.  But when using providers, all you need to do is this:
```js
import { render } from 'react-dom';
import theme from 'provide-theme';
import themesFiles from './themes/files';
import App from './components/App';

const props = {
  providers: { theme },
  providedState: {
    themesFiles,
    themeName: 'DarkTheme'
  }
};

render(<App { ...props } />, document.getElementById('root'));
```

Now, going back to the `@provide` decorator explanation, it wraps the `Foo` component with a new auto-generated component called `ProvideFoo(theme)`.  It gets the `theme` portion of its name from the fact that the `theme` provider has a `classes` reducer (see https://github.com/loggur/provide-theme/blob/master/src/index.js#L159-L168) and the `Foo` component wants a `classes` `propType`, so it knows to match up the `theme` provider with the `Foo` component.  And so your app's component tree looks something like this:
```html
<App>
  <ProvideFoo>
    <Foo />
  </ProvideFoo>
</App>
```

**Comment by jhabdas** [comment]
@timbur this work is very intriguing. please keep up the forward momentum!

**Comment by jugimaster** [comment]
So how do actions reach some other stores besides the one the action-emitting component belongs to?

If there's an event that affects a part of the UI somewhere else, with plain Redux you'd just dispatch an action and it would find its way to where you need it to go, because it goes everywhere! :)  

But what happens with this model?

**Comment by timbur** [comment]
Each provider has its own store which is instantiated at the top level.  The providers are then shared (via React's `context`) throughout all the components that need them; i.e., all these components are using the same provider(s) and store(s).  Actions are dispatched exactly as you would expect any other action would be using `redux`.

For example, if your provider looks like this:
```js
export const INCREMENT = 'INCREMENT';

const actions = {
  increment() {
    return { type: INCREMENT };
  }
};

const reducers = {
  count(state = 0, action) {
    switch (action.type) {
      case INCREMENT:
        return state + 1;

      default:
        return state;
    }
  }
};
```

And you have a component that uses the `increment` action:
```js
import React, { Component, PropTypes } from 'react';
import provide from 'react-redux-provide';

export default class IncrementButton extends Component {
  static propTypes = {
    increment: PropTypes.func.isRequired
  };

  render() {
    return (
      <button onClick={this.props.increment}>
        Click me
      </button>
    );
  }
}
```

And you have another component that uses the current `count`:
```js
import React, { Component, PropTypes } from 'react';
import provide from 'react-redux-provide';

export default class CurrentCount extends Component {
  static propTypes = {
    count: PropTypes.number.isRequired
  };

  render() {
    return (
      <div>
        Current count: {this.props.count}
      </div>
    );
  }
}
```

When you click the `IncrementButton`, the `increment` action is dispatched, and the `CurrentCount` component is immediately and efficiently updated with the new `count`, since both of the components are using the same provider (and thus, store).

And if for some reason you need to combine providers so that they use the same store and can listen for each other's actions, all you need to do is this:
```js
import { render } from 'react-dom';
import providers from './providers/index';
import App from './components/App';

const { page, pageWatcher } = providers;

const props = {
  providers: providers,
  combinedProviders: [
    { page, pageWatcher }  // the pageWatcher provider will now be aware of the page provider's actions
  ],
  providedState: {
    documentTitle: 'pretty easy right?'
  }
};

render(<App { ...props } />, document.getElementById('root'));
```

It's also possible to switch contexts and instantiate new providers within the middle of the component tree by simply passing another `providers` prop (and `providedState` and/or `combinedProviders`).

**Comment by timbur** [comment]
https://medium.com/@timbur/react-automatic-redux-providers-and-replicators-c4e35a39f1#.gl9gjp4wd

:)

**Comment by jhabdas** [comment]
Impressive!

**Comment by timbur** [comment]
v6.0 seems to work much better with `react-router` than v5 did.  There is now an official router provider at [`provide-router`](https://github.com/loggur/provide-router).  I like how it turned out so much that I'll be updating all of my examples/boilerplates to use it.

Huge thanks to everyone who pushed me in the right direction on this!  👍
