### ISSUE TITLE
Reserved component props should be less conflicting

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#30]
This is something that kinda struck me and I my eyes widened. A lot of names seems to be way too simple (eg. wait, query, clear) and easy for conflicting. I mean I would not certainly use such short names, but I can imagine that some people might want to do that. I am wondering what would be actual consequences of that as documentation doesn't really mentions that.

I think that every one of them should be at least prefixed with `provider` keyword to avoid possible conflicts and also to make it clear where that value is coming from.

**Comment by timbur** [comment]
The only `propTypes` that are actually reserved are `providers`, `providerInstances`, `activeQueries`, and `queryResults`.  I'll fix the docs so that it isn't confusing.  Perhaps those last 2 should have `provider` prefixed to them, but similar to my comment in #31, if you're building an app with this, there's little to no chance you'll inadvertently use these 2 `propTypes` when you shouldn't.  Beyond that, they were originally prefixed with `provider`, but it is actually no longer necessary even if you're using 3rd part components that use these `propTypes` because everything will still work the way they should - i.e., when you pass an `activeQueries` or `queryResults` prop to some component, the component will receive that prop (and not be overridden by providers).

The example(s)/tutorial(s) will make all of this much more obvious, I promise!

**Comment by timbur** [comment]
I clarified some things in the README.  Does that help with your concerns?  I also noticed that I forgot to remove `wait` and `clear` from that section, as those aren't actually used as props.  Those only exist directly on the `provider` objects and won't ever be passed to components, so feel free to use `wait` and `clear` props anywhere lol.  Sorry for the confusion!

**Comment by FredyC** [comment]
"Contextual" definitely sounds less scary then "Reserved" which makes impression that you cannot use those names. Much better description in overall for sure. Thank you.
