### ISSUE TITLE
Isomorphic application not possible?

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#31]
Just reading more through docs and this has kinda caused some shock to me...

> Sets the states of multiple provider instances, or if they don't exist yet, their states are cached on the **window.clientStates** object.

Doesn't that mean that whole module can be used in browser only? No isomorphic code? That sounds like awful limitation compared to pure Redux.

Looking [at the code](https://github.com/loggur/react-redux-provide/blob/master/src/createProviderStore.js#L20) it apparently expects the `window` to exists which surely wont in NodeJS.

On top of that I think it's very distasteful writing anything to global object. If anything, make it configurable please. What if someone uses same name of variable?

**Comment by timbur** [comment]
Isomorphic app is definitely possible.  And it's actually easier than vanilla Redux.  😁 

The `window.clientStates` object is designed to make isomorphic apps *easier*!  I suppose I could make it configurable, but how often do people actually use this exact variable?  The thing is, if you're already building an isomorphic app with this, there's little to no chance you'll be using this variable because you already know `react-redux-provide` uses it.

When the example/tutorial is ready, all of this will be much more apparent.

**Comment by timbur** [comment]
I'll add that part of the kinks I'm working out right now is specifically to make isomorphic apps 1000x easier.  I mean that you won't have to do any configuration whatsoever for isomorphic apps to work.  It will just work!

**Comment by FredyC** [comment]
I am confused. How can actually that code works in NodeJS which has no `window`?

**Comment by timbur** [comment]
There's no need to use it on the server since replicators handle all of the state initialization.  The `window.clientStates` object is only used client-side.

You will never actually have to think about this if you use [`provide-page`](https://github.com/loggur/provide-page).  See https://github.com/loggur/provide-page/blob/master/src/defaultRenderDocumentToString.js#L29.

**Comment by timbur** [comment]
There's no need to use it on the server since replicators handle all of the state initialization.  The `window.clientStates` object is only used client-side and during the initial render.  The `window.clientStates` object will actually be emptied by the very first provider component - i.e., within the very first tick of the application - so you'll actually be able to use that variable for any other purpose afterwards (though I can't imagine anyone would).

Beyond that, you will never actually have to think about this if you use [`provide-page`](https://github.com/loggur/provide-page).  See https://github.com/loggur/provide-page/blob/master/src/defaultRenderDocumentToString.js#L29.

**Comment by timbur** [comment]
One more thing: If you use provider boilerplate/generators, you won't ever need to think about this stuff.  Sure, it helps to know what's going on internally, but a huge part of what I'm working on right now is to make it so that it takes less than a minute to get started building things using the provider paradigm.  You'll see what I mean soon!  😁

**Comment by timbur** [comment]
Added some more info about client states to the README.  Are the changes in the above commit helpful?

**Comment by FredyC** [comment]
Ok, I am still not very comfortable with whole replication idea, I'll need to dive into that. But what you said and wrote into that commit makes me calm again. Thanks.
