### ISSUE TITLE
Composition of providers

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#34]
Currently I am bit experimenting with this because lately I am adopting concept called [stamps](https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0#.fsxpdjvd0). If article is too long for you, you can also check [stamp-specification](https://github.com/stampit-org/stamp-specification). It's essentially replacement for classes that allows you to compose together various information to obtain factory function used to create instances.

I've prepared [small gist](https://gist.github.com/FredyC/8f815f04b15b45e394889ad46e90a7e3) to show this in action. So far it's not much yet to prove itself. However idea is to essentially have only a single provider which will be composed from small bits into bigger thing. I kinda find that easier to reason about and also to handle various scenarios when you need access data from other provider.

Since these are instances, the `this` keyword is used. You can see it in `locateUser` [action](https://gist.github.com/FredyC/8f815f04b15b45e394889ad46e90a7e3#file-providers-usercity-js-L15) where I do access `this.request.findUserCity` which is just object with network related stuff. This comes very handy for tests as I can simply supply different object with mocks as you can [see here](https://gist.github.com/FredyC/8f815f04b15b45e394889ad46e90a7e3#file-test-_provider-js-L18).

I would like to know your opinion on this pattern. Do you see some obvious issue? Is it better to have multiple providers or a single one? Only possible problem I can thing of is probably hot reloading those providers, but I've never used it that much so it's not a big pain really.

**Comment by FredyC** [comment]
Ok did run into sort of issue now with this. When I call `this.props.locateUser()` from the component, obviously that function is executed in context of `props`. Since I need `this` to be actual instance of provider, it's kinda problem.

I have faked this in [tests here](https://gist.github.com/FredyC/8f815f04b15b45e394889ad46e90a7e3#file-test-_provider-js-L8) but it already felt terribly. Unfortunately I cannot do that in actual app, so that's gonna be a problem.

Do you think it would be feasible to actually bind those action creators to provider?

**Comment by timbur** [comment]
It's definitely better to have multiple providers and try to avoid combining them where possible.  I would also avoid relying on the use of `this`, because if/when React has a better API for `context`, these wrapper components will be unnecessary, as the future will likely be with stateless functional components.  This will allow all of the internals of provider handling to be pure functions (not classes), which is much easier to reason about and way more reliable, imo.  Easier to test too!  So yes, right now mostly everything is designed with the pure functions of the future in mind.

Back to your specific example... I think there is a lot of unnecessary complication/complexity happening.  This is definitely not the intended use of providers.  You should never have to manage any of the exports or explicitly call `instantiateProvider` yourself.

The intended usage is as simple as declaring `propTypes` on a component and passing to your top level component a provider (plain object) with `actions`, `reducers`, and/or `merge` matching some of those `propTypes`.  Anything more than that is most likely unnecessary.

As for composition, it is definitely possible to compose different providers into one, but how you do it really depends on the requirements.  I like stamps (I'm familiar with them), but most of the time, composition is as simple as this:
```js
import someProvider from './providers/someProvider';
import anotherProvider from './providers/anotherProvider';

export default {
  actions: {
    ...someProvider.actions,
    ...anotherProvider.actions
  },

  reducers: {
    ...someProvider.reducers,
    ...anotherProvider.reducers
  }
};
```

Sure, we could introduce some utility that does simple things like that for you, but I personally prefer fine-grained control, because it allows more complex, (real-world) functionality.  For example, straight from [`provide-user`](https://github.com/loggur/provide-user/blob/master/src/index.js):
```js
import provideCrud from 'provide-crud';
import provideAuthentication from 'provide-authentication';

const user = provideAuthentication(provideCrud('user', { name: '' }));

export default user;
```

The resulting functionality would not be possible with a simple combination, because there are more complex things like replication to consider (i.e., what the client should see vs what the server should see), which requires fine-grained control.  But while the internals require full control, the external API is now extremely simple as seen in the code above, and that's what we want!

Today I should finally be able to put together a good example/tutorial which will show the intended usage and how easy it really is.  And after than I will be comfortable removing all of the confusing stuff from the README, moving it to proper documentation, and replacing the README with something concise that shows only the intended API.  Sorry that it isn't clear yet.  I wish I could have gotten all of this finished faster!

**Comment by FredyC** [comment]
Hm, so I just spent like 3 hours figuring it out and now you say me I should do it like this. Yay! :) 

How would you approach problem of dependency injection? That's kinda main reason why am I doing it this way. Thanks to that I can write tests [easily like this](https://gist.github.com/FredyC/8f815f04b15b45e394889ad46e90a7e3#file-test-cityname-js-L9). I cannot really imagine how it would be possible with _pure_ providers.

I am calling `instantiateProvider` only for purpose of unit testing as you've adviced me. I surely do not intend to do it elsewhere.

I've updated gist with working version now. Thanks to latest changes I can now use `providerInstance.actionsCreators` as you mentioned before. Definition of provider is more simplified as well.

**Comment by FredyC** [comment]
Ok I've come to conclusion that composing providers like this isn't best idea, so I am closing this. I did handle dependency injection with a factory function. Just for anyone interested, this is how my `providers/index.js` looks like.
```js
import Request from 'core/request';

const requireProvider = require.context('providers', false, /\.js$/);

const providers = [
	'config',
	'locale',
	'userLocation',
	'citySearch',
	'focusable',
];

export default function createProviders() {
	const options = {
		request: Request.create(),
	};

	return providers.reduce((result, providerName) => {
		let provider = requireProvider(`./${providerName}.js`).default;
		if (typeof provider === 'function') {
			provider = provider(options);
		}
		return { ...result, [providerName]: provider };
	}, {});
}
```
