### ISSUE TITLE
Nothing seems to be provided to the component

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#35]
Well so after I've created the provider, made some unit tests for it, now with attempt to actually make it work with component seems it doesn't work for some reason. You can see the provider code in the [gist](https://gist.github.com/FredyC/8f815f04b15b45e394889ad46e90a7e3). Here is my component.

```js
const ChooseCity = ReactStamp.compose({
	displayName: 'ChooseCity',
	propTypes: {
		cityName: ReactStamp.PT.string.isRequired,
		locateUser: ReactStamp.PT.func.isRequired,
	},
	render() {
		return (
			<div className={styles.component}>
				<CityInput
					value={this.props.cityName}
					onChange={this.props.locateUser}
				/>
			</div>
		);
	},
});

export default provide(ChooseCity);
```

Then there is a top level render where I am passing providers like this.
![image](https://cloud.githubusercontent.com/assets/1096340/16336157/9a214748-3a0b-11e6-88a1-861a21ce6ee4.png)

When I look at `ChooseCity` component there, it has none of those props...
![image](https://cloud.githubusercontent.com/assets/1096340/16336216/1268258c-3a0c-11e6-9f8c-7a7f04f406a6.png)

Do you have any idea what might be wrong here?

**Comment by FredyC** [comment]
Ok so I wrapped that top level component into `provide` as well and that seems to solve issue. This is seriously missing from documentation and it's not even in examples, so it's really strange.

**Comment by timbur** [comment]
Hmm that is a strange way to use providers, but I guess it works.  😀 

The docs say to use `react-redux-provide/lib/install`, but I agree that it is kind of buried.  I'm also aware that this method makes things kind of ugly in React's dev tools, as it wraps every component, but that's unavoidable right now.  I am trying to get better support for automatic contextual/wrapper components in the next version of React mainly so that the view in dev tools won't look so silly.  Even with every component wrapped with the `<Provide/>` component, everything is still extremely efficient because it's cached and only updates when state or props change.

But anyway... I made it obvious to use the `install` method at the top of the README.  👍

**Comment by FredyC** [comment]
That's not really what I am looking for :) I don't want to use `install`, I just don't like that approach. Is it ok then to wrap that top level component manually with `provide`? Will it work same way? So far it seems so. In that case it would be nice to mention that in docs as well. In that quick example you do offer 2 methods, but for other method you just don't say about wrapping this top level component.

**Comment by timbur** [comment]
Yes, I'll add to the README the bit about having to wrap the top level component.  It is necessary so that the `providers` can be passed down via `context` from the top.

**Comment by FredyC** [comment]
Yea, I was really confused at one moment realizing that I am passing `providers` to top level component, but you don't have access to that component from anywhere, so how the hell you could get those into context. So I tried to wrap it and it worked :) I am really looking forward to updated readme and tutorial to get rid of the confusion.
