### ISSUE TITLE
Querying 3rd party API

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#36]
This may be more related to redux itself, but it's kinda more apparent with providers since actions creators and reducers are in a same file. I've a kinda hard time to establish some clear convention on how to name these. I guess basic rule can be that action creators are verbs and reducers more like nouns...

Let me show you example. I have action creator called `searchForCity` which returns thunk and dispatches different actions based on results of the search. When no cities are found I use `cityNotFound` creator. Am I just bad at english, but this isn't verb already, right?

When multiple results I found I use creator `foundCities`. And here I come to sort of conflict because I can only think of the same name for reducer, but that's super confusing.

There is also a logic when only single city is found, it gets automatically selected for user, so I have a creator `selectCity` (that's surely verb) and reducer is named `selectedCity`.

Do you have an idea how to get from that mess, please? Only way I can think of is using prefix `set` for those creators that sound like noun, or more likely to all creators, but how would I rename `searchForCity` in that case?

```js
const reducers = {
	selectedCity: {
		selectCity(state, city) {
			return city;
		},
	},
	foundCities: {
		searchingForCity() {
			return null;
		},
		foundCities(state, cities) {
			return cities;
		},
	},
};
```

**Comment by timbur** [comment]
What does the API look like for the backend?  Do you own (have control of) the database and the server it's on?

**Comment by FredyC** [comment]
I don't see much of relevance, but no, I don't have any control of it. API looks like I call `GET /places/?term=${searchTerm}` and I get back json array. Not exactly any kind of standard.

**Comment by timbur** [comment]
Okay, just curious.

The way you have it setup now is sort of okay, but I think the best solution is a replicator designed specifically for your API requests.  Then the rest of your app is declarative.

Your replicator might look something like this:
```js
import fetch from 'fetch';  // HTML5 Fetch API

function getUrl(key, reducerKey) {
  // assuming you can get info for specific places via some URL like
  // places/cityName/cityInfo
  // you'll need to determine the best way to build this URL
  // from the provider `key` and the `reducerKey`
  return `/places/${key}/${reducerKey}`;
}

function getQueryUrl(query, options) {
  return `/places/?${buildQueryString(query, options)}`;
}

function getInitialState({ key, reducerKey }, setState) {
  const url = getUrl(key, reducerKey);

  fetch(url)
    .then(response => {
      return response.json();
    })
    .then(state => {
      setState(state);
    }).
    .catch(error => {
      setState();
    });
}

function onStateChange({ key, reducerKey, queryable }, state, nextState) {
  // if you're pushing data to the API, you can do it here
  // if not, don't worry about including this function
}

function handleQuery(query, options, setResult) {
  const queryUrl = getQueryUrl(query, options);

  fetch(url)
    .then(response => {
      return response.json();
    })
    .then(result => {
      setResult(result);
    }).
    .catch(error => {
      setResult([]);
    });
}

const placesApiReplicator = {
  getInitialState, onStateChange, handleQuery
};

export default placesApiReplicator;
```

I would have a provider for cities (i.e., a `city` provider), and a provider for states (i.e., a `state` provider), but we'll just focus on the `city` provider to avoid any confusion.  And it would look something like this (note that the reducer keys match the `getInitialState` portion):
```js
const key = ({ props }) => props.stateName && props.cityName
  ? `state=${props.stateName}&city=${props.cityName}`
  : null;

const actions = {
  // do whatever with the current city
};

const reducers = {
  cityName: (state = '', action) => state,
  cityInfo: (state = '', action) => state
};

export default { key, actions, reducers };
```

And then all you have to do is write your components like this:
```js
import React, { PropTypes } from 'react';

const SomeCityInfo({
  classes,
  cityName,
  cityInfo
}) => (
  <div className={classes.SomeCityInfo}>
    <h3>Info for {cityName}:</h3>
    <div>{cityInfo}</div>
  </div>
);

SomeCityInfo.propTypes = {
  classes: PropTypes.object.isRequired,  // use `provide-theme` imo
  cityName: PropTypes.string.isRequired,
  cityInfo: PropTypes.string.isRequired
};
```

And then when you pass a `cityName` prop to that component, the provider will be created using its provider `key` function, which will then retrieve the info from the API and automatically provide the component with the relevant `cityInfo`.

Similarly, you can declare exactly what you want queried.  So suppose you want to retrieve a list of cities matching some info:
```js
import React, { PropTypes } from 'react';

const SomeCityNames({
  classes,
  result
}) => (
  <div className={classes.SomeCityNames}>
    <h3>List of city names:</h3>
    <div>{JSON.stringify(result)}</div>
  </div>
);

SomeCityNames.propTypes = {
  classes: PropTypes.object.isRequired,  // use `provide-theme` imo
  cityInfo: PropTypes.string.isRequired,
  query: PropTypes.any,
  queryOptions: PropTypes.object,
  result: PropTypes.any
};

// you don't have to do this, but I think it's nice so that you can just pass the `cityInfo` prop
// otherwise, you'd need to pass the full query object (or string) yourself
SomeCityName.defaultProps = {
  query: ({ props }) => { cityInfo: props.cityInfo },
  queryOptions: {
    select: [
      'cityName'
    ]
  }
};
```

I actually just published a tutorial article this morning that might be helpful:
https://medium.com/@timbur/bridging-the-gap-between-redux-and-the-declarative-nature-of-relay-graphql-tutorial-45a0bf5bd13a

**Comment by FredyC** [comment]
You went completely different direction than I've asked :( I don't have a concern about querying 3rd API at all. Perhaps read my original comment again? I am just trying figure naming conventions, nothing else really...

Frankly I do find your replicator solution way too over engineered for my small needs. Thanks for trying to show me it, but that's that not what I want.

**Comment by timbur** [comment]
The naming conventions and how you should approach the design of the app (i.e., how you get data from 3rd party APIs to your components) are two sides of the same coin.  The replicator solution is really simple, I promise.  I don't think it's over engineered at all, because if you take a closer look, you have to perform those API requests anyway, don't you?  And that's all the replicator does.  It allows you to make declarative API requests.  It requires a small shift in thinking but I promise that once you're there, you'll realize it's a much better design.

**Comment by FredyC** [comment]
I don't agree really. I don't want to really care about way of retrieving data, I have that wrapped in a separate module and I want to keep it like that. Call me old school, but I am not mentally ready for replicators yet. I do a single GET request which I fit into like 4 lines of code. Currently I don't see benefit of having code for like 30 lines doing same thing just because "it's declarative".

```js
async function searchCity(term, locale) {
	const queryData = { term, locale };
	const response = await this.request(`${skypickerUrl}/places?${qs.stringify(queryData)}`);
	const places = response.body;
	return places;
}
```

So if you cannot help me with my problem I guess I'll have to figure out something on my own.

**Comment by timbur** [comment]
Also, as for how all of that relates to the naming conventions, when you shift to the declarative style of API requests, it allows you to think of your providers as models you use to simply represent some data, rather than a way to imperatively retrieve that data.  This makes *everything* easier.

FYI, you could definitely fit all of that into a tiny replicator, < 20 lines of code.  What I wrote above was only lengthy because I wanted to be thorough.

That said, you can continue to do your requests as you currently are, since everything you can do with Redux, you can do within providers.  There's nothing wrong with the way you're doing it now.  But you did ask for what I thought was a better way, so I told you.  😄

**Comment by FredyC** [comment]
Well yes, I asked that "how to get out of the mess". Should have been more specific what mess :) It was really only about names.

I don't actually like polluting propTypes like you did. I would rather specify there that I am expecting props like `cityName` or `foundCities` and just render based on that. This declarative way kinda feels like mixing together presentation and logic again and I don't want to do that. I want to have pure components as much as possible without bothering them with details about data retrieval.

Thanks anyway, perhaps one day...

**Comment by timbur** [comment]
I'm not sure what you mean about polluting propTypes.  All of those props are used.  The `foundCities` prop and the `result` prop are one in the same.  And it is all presentation, no logic.

For example, if you want to display some info for a specific city, this is all you would need:
```js
<SomeCityInfo cityName="New York City" />
```

And that component would be automatically provided all of the info it needs for other matching propTypes like `cityInfo`.

As for how `foundCities` and the `result` prop are the same, going by my above `SomeCityNames` example, you could find cities matching any info by simply declaring the component like this:
```js
<SomeCityNames cityInfo="Fun!" />
```

And that component would automatically have the `foundCities` as its `result` prop.  Then you would of course render whatever you need by using the `result` prop just like it was your usual `foundCities` prop.

Anyway, I hope that's more clear now.  And I completely understand just wanting to get something finished and not worry about switching to a different paradigm!

**Comment by FredyC** [comment]
And what about `query` and `queryOptions`? Those are not really used there and they are specified.

Btw, how you fit into this declarative approach input from user? Obviously searching for city means that user has typed something, I run a request, update state and re-render.

**Comment by timbur** [comment]
The `query` and `queryOptions` are what creates the `result` prop.  The `query` prop is a function of the `cityInfo` prop, which was passed here:
```js
<CityNames cityInfo="Fun!" />
```

The internals of the component are still presentational, as there is no logic to the `query` function prop.  It's just a shortcut to make things quicker/simpler, as it doesn't require you to wrap your component in a container component to handle the query.

So if you wanted to search for `cityInfo` based on user input, it would be as simple as this:
```js
import React, { PropTypes, Component } from 'react';
import CityNames from './CityNames';

export default class CitySearch extends Component {
  constructor(props) {
    super(props);
    this.state = { cityInfo: '' };
  }

  render() {
    return (
      <div className={this.props.classes.CitySearch}>
        <input
          type="text"
          placeholder="Search"
          defaultValue={this.state.cityInfo}
          onInput={event => this.setState({ cityInfo: event.target.value })}
        />

        <CityNames cityInfo={this.state.cityInfo} />
      </div>
    );
  }
};
```

**Comment by FredyC** [comment]
Uh, local state, really? And you find that nice along with replicators and stuff? :) What about ability to have a state of application properly contained and easy to serialize for example?

I guess I know meaning of `query` and `queryOptions` but that's a pollution I am talking about. You are not actually using these anywhere in that component.

**Comment by FredyC** [comment]
Also you haven't really covered scenario that I am calling network API based on that input, there needs to be action dispatch

**Comment by timbur** [comment]
It doesn't have to be local state.  A provider could handle input as well.  No problem there.  😀   (BTW, local state isn't bad for acting on temporary things like user input, and it's actually what the folks at Facebook use and recommend).

As for storing/serializing application state, that's exactly what replicators are designed to do - i.e., that's what the `getInitialState` and `onStateChange` functions are for.  For example, see [`redux-replicate-localforage`](https://github.com/loggur/redux-replicate-localforage).  All you do is add that replicator do the client's providers and it works without any extra setup (assuming you already have the provider's `replication` defined).

People seem to have this idea that application state is separate from things like user data that you'd retrieve from a database, for example.  Think about it.  User data is just a representation of that user's current state - their name, their current status, etc.  It's all actually the same thing, so you can use the same methods to manage it.

So you can use a replicator designed to locally store/serialize certain application state, and you can use another replicator designed to retrieve the state (i.e., data/information) of things like cities from external data sources.

The network API *is* called based on that input, but by the replicator.  The difference is that there is actually no need to put actions within your UI.  They don't belong there anyway.  Ideally, with the maximum separation of concerns enabled by providers + replicators, creating your UI and adding features is just a matter of declaring, "I want the UI to look like this."  And everything just works.

**Comment by timbur** [comment]
Also, you *could* dispatch an action to handle the input and perform the query within a provider if you wanted.  Nothing is stopping you from doing that.  But I think a maximally declarative UI design where just everything works exactly how you've laid it out... is much better.

**Comment by FredyC** [comment]
I am still unable to imagine how would that work. How can input from user be propagated into replicator within component to actually fetch data?

**Comment by timbur** [comment]
Replicators are an optional property of providers, so they don't exist within components at all.  They just make it easy to automatically store/retrieve any state (data) that the provider needs.  Emphasis on "automatically retrieve".  You don't need to explicitly fetch data.  You just specify, as a propType on the component, that you want some prop (i.e., data/state/whatever you want to call it).  The provider will use the optional replicator to retrieve the data the component needs.  So to make that work with user input, it's just a matter of passing the input value to some component that you know a provider will provide data for, based on that input value.

**Comment by FredyC** [comment]
> So to make that work with user input, it's just a matter of passing the input value to some component that you know a provider will provide data for, based on that input value.

Hm, that's way beyond my imagination. So to make that work I would have to wrap that input into some other component along with "invisible" one to which I sent value from local state. And that component would do what with it? Doesn't need to dispatch action anyway? I am still not getting how that value would propagate from props back to provider to initiate replication. 

I mean, when component is wrapped into `provide` you have access to its props, I get that. But based on what logic that value would get into provider to initiate network request? I assume it has something to do with that strange `query` prop?

Even like this it seems kinda awkward to me. You need bunch of "invisible" (don't better name for it) components just to pass values way to top? How does that feel easier then just dispatching action? I mean doing simply `<input onChange={evt => this.props.searchCity(evt.target.value)}` is essentially also declarative to me. Except that dispatch is not going through replication I suppose.

**Comment by timbur** [comment]
I'm happy to answer all questions.  😅 

There are multiple ways to do it.  It all just depends on your requirements and how flexible/reusable/decoupled you want your components to be.

In my opinion, the best design makes the component structure as simple and concise as this:
```js
<InputToProps name="cityName">
  <CityInfo />
</InputToProps>
```

This is mostly a conceptual example to answer your specific question, but you could certainly easily implement this if you wanted.  This structure allows for maximum reuse of both components while makes it really obvious as to what's going on when looking at the UI code, right?  The `InputToProps` component will take its input value and pass it as a prop to its children (using its `name` as the prop key).  You could use that anywhere.  And the `CityInfo` component should just receive some `cityName` and would display info for it, when could also be used anywhere.  So in this case, we put these two decoupled components together such that the input value will be passed as a `cityName` prop to the `CityInfo` component.

Now remember that providers can use a `key` function to differentiate themselves, and this `key` function receives the component instance as its first argument, which allows you to provide specific data to some component based on the component's props.  Because when the store is instantiated (based on what the `key` function returns), it gets its initial state from your replicator's data source - i.e., it passes the result of the `key` function to the replicator's `getInitialState` function.  This is where the network request is made.

So let's pretend we have a `city` provider which has a state shape (reducers) like `cityName`, `cityLocation`, `cityPopulation`, etc.  (You can actually use [`provide-crud`](https://github.com/loggur/provide-crud) to create these in just a few lines of code.)  When the above `CityInfo` component receives the `cityName` prop, we can set the `city` provider's `key` to return something like `cityName=${props.cityName}`.  This would ensure a provider store is instantiated specifically for that particular `cityName`, and the replicator will get the initial states (`cityLocation`, `cityPopulation`, etc.) for that particular `cityName` from the API.

In short, if the `CityInfo` component wants the `cityLocation` and `cityPopulation` for some specific `cityName`, all you have to do is this:
```js
// src/providers/city.js

providers.city.key = ({ props }) => `cityName=${props.cityName}`;
```
And this:
```js
// some place where we want to render CityInfo
<CityInfo cityName={someCityName} />
```
^ That will have a provider specifically for its `cityName`, which means it will be provided the `cityLocation` and `cityPopulation` for that `cityName`, automatically retrieved via the replicator's `getInitialState` function when the store is instantiated.

And so you combine that with some component like the above `InputToProps` example, which always passes its input value as `cityName` to the `CityInfo` component.

Queries work almost exactly the same.  But instead of `getInitialState`, it uses the replicator's `handleQuery` function.  So suppose you want to find all city names matching some `cityInfo`, the most concise way is this (with the internal `CityNames.defaultProps.query: ({ props: { cityInfo } }) => { cityInfo }`):
```js
<CityNames cityInfo={someCityInfo} />
```

But if you don't like using the `query` function internally (which makes it possible for the above to be so concise), you can explicitly specify the query:
```js
<CityNames query={{ cityInfo: someCityInfo }} />
```

And last but not least, I'm sure you're wondering, "Why can't I just use the `CityInfo` component or the `CityNames` component without wrapping them with `InputToProps`?"  You could.  And you could put the `input` directly within them and dispatch an action to get the props you want from the network.  But there are 3 drawbacks to this:

1.  You'd be running into the same weird names like `searchForCity` and `cityNotFound` for your actions.  And you know why they seem weird and why using them seems sort of cumbersome?  Because these things shouldn't actually be actions.  All you should ever need (or want) within the app's UI is to declare, "I want this data" and "I want to update this data".  Anything more than that (like dispatching actions to fetch data or even then dispatching actions to specify that you haven't found something) is too complicated for UI, I think.  

2.  If you didn't wrap them with an `input`, the `CityInfo` and `CityNames` would need to have the `input` inside of them right?  This makes them less reusable.  Or if you wanted to make the internals more reusable, you'd separate them out into their own components.  But then guess what?  Now you're essentially implementing the `InputToProps` wrapper, just in a more complicated, less reusable form.

3.  It's all just functions.  There are no invisible layers.  There are only functions that props pass through and props that are automatically extracted via `context` (where the providers actually "live").  The providers + replicators are doing the *exact same thing* that you would when dispatching an action to get some data.  The only difference is that once you understand what exactly is happening, it's much easier to follow, because it leads to more concise, readable, and reusable/decoupled code.  It will also save development time because it's automatic, and you're able to 100% declare what your UI will look like, and everything will just work.

**Comment by FredyC** [comment]
Whoa, I will have to reread whole thing here couple times before I even start understanding it :) Thank you for your patience.

**Comment by FredyC** [comment]
Ok, I really tried to understand it and I am think I am getting some basics. The best would to apply it my real use case so I can learn from it. So if you can help me with that, it would be much appreciated.

First task is essentially simple. When user enters application I need to query remote service which returns json data about user location by IP, so there is no input from user. I can imagine it could be simple like this...

```js
function getInitialState(noNeedThis, setState) {
	this.request.findUserLocation()
		.then((result) => setState({
			city: result.city,
			latitude: result.lat,
			longitude: result.lng
		});
}
const replication = { getInitialState };
```
However can I actually dispatch actions here? In your examples you are just setting some empty value to state within `catch` but what if I want to propagate actual error somewhere else? Perhaps even another provider (which I don't have yet) that would replicate errors to some external service?

Also I would like to dispatch action to actually inform user what is happening. There will be sequence of various other steps after this one and I want to display message to user showing what is happening instead of just animated gif.

**Comment by timbur** [comment]
Can you describe exactly what you need to do?  It might be easiest for me to implement and show you a small example that matches your requirements.

**Comment by timbur** [comment]
Actually you did sort of describe what you need to do.  So I guess I should ask, is there a public API I can use to show you?

**Comment by FredyC** [comment]
Yea, it's public service ... http://ip-api.com/json

I am not sure what else to add. But there will be next step which uses retrieved geo location to find another nearby cities based on various criteria, but let's focus on small things first :)

**Comment by timbur** [comment]
I should have time to write something for you later on.  But quick question first, do you want users to be able to login and all that?  I.e., will they have user IDs and user names?  There are a couple of different ways to do this but the best way depends on the exact requirements.

**Comment by FredyC** [comment]
No users, it's simple app doing some search and displaying results. No real backend or database. Well I should probably be little more specific in those additional steps because they are actually relevant for architecture of a whole thing.

1. Discover user geolocation (with that service)
2. Run it through algorithm that has list of POI (bundled with app, no remote request)
3. It should find out like 5 closest ones (number can be changed by user). 
4. Run remote request for each of those found POI to get some more information about these. It is the service I mentioned before `http://foo.com/places/?id=ID` where ID comes from those found POI
5. Display those POIs to user
6. User can input different origin location and we go back to point 2

So essentially if I would have a single store, I could imagine state something like this. That is assuming that I don't actually need any actions and can achieve it with your declarative way.
```js
{
	originLocation: 'valueToDisplay',
	numberOfLocationsToFind: 5,
	foundLocations: [
		'location1', 'location2', 'location3' // can be less locations
	],
	progressMessage: 'Finding your location...', // i18n
	errorMessage: 'Something went wrong', // i18n
}
```

**Comment by FredyC** [comment]
Hmm, I think it's slowly starting to make sense. I see that `getInitialState` has store available for dispatching actions, that's super helpful, but `handleQuery` doesn't. So how can I handle error states there or dispatch action about progress?

Also how does it actually work when I at first have `<OriginInfo locationIp="" />` and then I change it to `<OriginInfo locationIp="1.2.3.4" />`? It will always call `getInitialState` again? Or where can I actually fetch new data based on that change?

**Comment by timbur** [comment]
It will create a new provider based on the `locationIp` prop (since the provider `key` is a function of that prop), which will go through the initialization process again (but this time for the new `locationIp`).  The old provider will remain.  You can use as many of these components+providers at the same time as you want.  When the `locationIp` is the same across different components, they will use the same provider+store.

I can't think of a good way for `handleQuery` to interact with a particular store to dispatch an action for an error, because `handleQuery` doesn't actually use any stores.  It's specifically for the database/API queries, which means there are no stores linked to it (otherwise, there would be potentially thousands of stores since the query is essentially for states throughout all stores).  I think maybe the best thing would either be to add another special prop, `queryError`, or leave it as an implementation detail for the `result` prop.  (I think `queryError` is better though.)

**Comment by FredyC** [comment]
Ah, now it makes sense. By defining key I am having different provider for a different user input. So essentially when user types in same value again, I would get back same provider and no request would be sent out anymore. That's actually handy, but can be also old providers thrown away somehow? Perhaps it's premature concern about memory.

But what happens when I actually dispatch `setLocationNumberToFind` which will change that parameter in a store, but how it will know that it needs to run a new fetch of data? I would be sort of expecting to use `onStateChange`, but there is not `setState` argument to actually update data based on new fetch.

Hm, `handleQuery` sounds bit odd to me. It runs a query against API but doesn't store results anywhere? How that can be useful?

**Comment by timbur** [comment]
The example code I gave you want written with the assumption that you'll only be getting location info for only a handful of IP address (or usually just 1).  But yeah at some point I might implement an LRU algorithm for the provider instances.  But ideally it wouldn't really be necessary, because when you're finding something, you shouldn't be creating a provider instance for each result.  If you're doing that, then you should actually be using the query stuff (and you could then use a single result selected by the user or something to create a provider instance that you actually need).

The query result is passed as the `result` prop.  Each query is also temporarily cached within `context.queryResults`.  It's removed from the cache shortly after the query is done, and I could add a timeout or a way to manually uncache if people deem it necessary.  But typically, when querying things, you almost always want up-to-date results.  There is also [`redux-replicate-memory`](https://github.com/loggur/redux-replicate-memory) (and other client-side replicators like [`redux-replicate-localforage`](https://github.com/loggur/redux-replicate-localforage)), which is another way to store the query results on the client indefinitely, but only if you have your providers setup correctly.  We won't dive into that right now though.  😉 

If you look closely at the call to `provideCrud`, I made a comment about the `numberToFind`.  That might need to go into its own provider, which you could then use anywhere, within queries, etc.

**Comment by FredyC** [comment]
Actually I won't by using any IP there. That service simply returns information for the client that calls it, that's all I need for initial location. But user can then input different location (like a name of the city) and it would yield different list of POIs. So you say not to use `key` to have a provider for each result, but rather go with query?

I am still rather unclear on how these queries work. What if you have actually two separate component and each is asking for some data through query? How you would decide which provider is going to handle that? I assume based on other propTypes, but what if there is actually mix of those and 2 providers would fit there?

**Comment by timbur** [comment]
Oh, sorry for the confusion.  A provider technically does handle the query, but it's always the base provider with no instance behind it.  It might be possible to use a provider instance for the query if the `query` prop is within a component with a provider instance assigned to it.  And then it could have the store passed to the `handleQuery` function.  Let me think about that.  I think it might actually be easy to do and it might make sense.

Right now the base provider that handles the query is determined the same way as props - i.e., it looks for a matching prop.

Dispatch actions specific to user events, something that explicitly changes the state of the store.  But use replication for cases where you simply want to say, "Give me this data".  That's the main difference.

**Comment by FredyC** [comment]
No, that's not what I meant. When you have multiple providers, like different ones (not instances) that are required by a single component. How does it pick which provider handles query? Or is not no longer true that component can receive props from multiple providers? I remember it was possible earlier.

**Comment by timbur** [comment]
Yes multiple providers are still assigned to components (note the use of the `classes` prop in the above examples).

Regarding dispatching action to retrieve data: The difference is that in most cases it's unnecessary and doing it like that is how you end up with an odd mix of naming conventions for actions and reducers, as it becomes a mix of more imperative code than declarative.

**Comment by FredyC** [comment]
> Yes multiple providers are still assigned to components (note the use of the classes prop in the above examples).

That's good, but you haven't actually explained how queries are handled than. Which providers is chosen when there is a more of them? Every one of them? Doesn't that override result with last one?

**Comment by FredyC** [comment]
Also I find `getInitialState` and its `setState` somewhat strange as it is apparently changing state directly. Haven't you considered that it should actually dispatch action so that reducer can actually decide how the new state will look like instead of just replacing whole thing? I had to look into source code about this because I was rather confused what's the magic behind it and what action I am going to receive there.

**Comment by timbur** [comment]
From my earlier comment:
> Right now the base provider that handles the query is determined the same way as props - i.e., it looks for a matching prop.

This applies to queries for multiple providers within the same component as well.  I don't really recommend querying multiple providers within the same component though, because their results are merged into the `result` prop.  Splitting up the queries per provider within individual components is the best way to go.  But if you must use multiple queries, just use the `queries` and `results` props instead.  See the README: https://github.com/loggur/react-redux-provide#queries

In what scenario would you want to immediately change the state that's being initialized?  Seems like a design flaw.  Whatever you'd be changing the state to should be the initial state anyway.  But I suppose it would be good to dispatch an action during `setState` so that it would show up in dev tools.  I'd recommend against actually using it though (just like Redux recommends against doing anything with its `INIT` action.  There is also a small problem with setting state, and that is how Redux is designed.  It was never designed to explicitly `setState` (or asynchronously initialize the state after the store is actually created) so I had to wrap all of the reducers with a higher order reducer that explicitly overrides the current state of things.  Dispatching an action to do would still work though.  I guess the problem to solve (if I wanted to allow using the `setState` action) would be... how to override the state while allowing the developer to override that state at the same time?  The only thing I could think of would be to compare 3 things: before, during, and after.  But that seems like it would be prone to bugs for things like strings and numbers.

**Comment by FredyC** [comment]
Ok thanks for explanation.

> In what scenario would you want to immediately change the state that's being initialized? 

Ok I guess that's another way how to look at it. I meant to have a more control about how the state should look like instead leaving that up to replicator, but what you are saying makes sense I guess.

--------
Would you actually recommend separating components that are merely about visual representation from those that runs logic through declarative approach? I am still kinda struggling about some general approach to this. Returning back to my earlier comment describing part of my logic I need to achieve...

 2) Run user location through algorithm that has list of relevant POI (bundled with app, no remote request)
 3) Look up for 5 closest ones by user location (number can be changed by user).
 4) Run remote request for each of those found POI to get additional information about these. It is the service I mentioned before http://foo.com/places/?id=ID where ID comes from those found POI

These are essentially background tasks without user input. I am still unsure if I should like wrap it into a single provider and just wait for final results or if I should have a single component that will be deciding about next step.

**Comment by timbur** [comment]
Sounds like you should strive for a component structure like this (and this is where React really shines, I think):
```js
<Origin locationIp="">
  <ClosestPOIs>  // pass numberToFind to this component, either by Origin or by a provider
    <POI/>  // the ClosestPOIs component would run the query
    <POI/>  //  and these POI components would be generated as children based on the result
    <POI/>
    <POI/>
    <POI/>
  </ClosestPOIs>
</Origin>
```

**Comment by timbur** [comment]
Just to clarify the comment "the ClosestPOIs component would run the query", you could have a provider with simple reducer(s) like `poiNearby`.  And then your `Origin` component would pass some location (which it received from the `location` provider) to the `ClosestPOIs` component as a `poiNearby` prop.  The `ClosestPOIs` component would turn that into its `query` prop (`ClosestPOIs.defaultProps.query = ({ props }) => { poiNearby: props.poiNearby }`), and would eventually receive the result as its `result` prop.

**Comment by timbur** [comment]
Alternatively, instead of using `ClosestPOIs.defaultProps.query`, you could just explicitly pass the `query` prop from the `Origin` component to the `ClosestPOIs` component as `query={{ poiNearby: props.someValidLocationFromOrigin }}`.

**Comment by FredyC** [comment]
Ok, that sounds very interesting. If I understand correctly, these components would just run the logic, they would not actually render anything. And that's what I am curious about. Currently I have a `components` folder with all of them. Then I have a `containers` which essentially combines those components together. I am thinking if there should be some other folder with logic components only so it's easier to navigate among them. Or maybe subdirectories (within `components`) like `view` and `controller`? It just feels rather strange to mix these two types together.

> Alternatively, instead of using ClosestPOIs.defaultProps.query, you could just explicitly pass the query prop from the Origin component to the ClosestPOIs component as query={{ poiNearby: props.someValidLocationFromOrigin }}.

I was kinda thinking about it why it. You are always using `defaultProps` for `query` it seems, but it feels bit strange since it's suppose to run logic, why it should be like _default_? On other hand `ClosestsPOIs` should know better about what it needs to query while `Origin` is about something different.

**Comment by timbur** [comment]
All you need is a `components` directory and a `providers` directory.  These components might render things to the DOM, they might not.  That's up to you.  And you really wouldn't be mixing anything.  You're simply declaring, "This is the structure I want".  You know the components will always render certain things, and as far as the component/UI structure goes, how they get the data should be of little concern to you (i.e., no "containers").  Getting the data and providing that data to components is up to the providers.

**Comment by FredyC** [comment]
I do consider "container" more like "layout" component to glue everything together. Those little components doesn't know anything where they will be on a screen. I guess it's matter of perspective.

Ok thanks once again, I think I have enough information for now, so let's see if I can make something from it.
