### ISSUE TITLE
Error handling and progress reporting with providers

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#37]
I am either missing something or it seems to be overly complicated with providers. With pure redux and its single store I would just dispatch an action with error/progress information and some reducer would update appropriate part of a state based on that. Then component would get rerender and I would just display value from a state.

Now with providers I am failing to see a simple way how to do it. Considering following provider. I tried to do something similar as described above, but then I realized that store is isolated I cannot handle those actions in a different provider.
```js
import { actionValidator } from 'validator';
import { createSchema } from 'redux-action-schema';

const schema = createSchema([
	['locatingUser'],
	['userLocated', actionValidator.userLocation],
	['userNotLocated'],
]);

const types = schema.actions;

const actions = schema.actionCreators;

const reducers = {
	location: (state = null) => state,
};

function UserLocationProvider({ request }) {
	async function getInitialState(_, setState, store) {
		try {
			const location = await request.findUserLocation();
			actionValidator.userLocation(location);
			setState(location);
			store.dispatch(actions.userLocated(location));
		} catch (err) {
			store.dispatch(actions.userNotLocated(err));
		}
	}

	return {
		types, actions, reducers,
		replication: {
			replicator: { getInitialState },
		},
	};
}

export default UserLocationProvider;
```
I certainly don't want to end up with storing progress/error message in this provider because there will be a bunch of other providers with same problem. Just imagining I would have a component with propTypes for each separate error/progress message from state and displaying them conditionally makes me feel rather sick.

I am thinking if `subscribeTo` can be somehow used for this? I would have a provider for all error/progress states which would subscribe to other relevant providers. Then I would probably had to use `store.subscribe` to listen for action. But once again considering how easy it is with pure redux, this feels like total hell :(

**Comment by timbur** [comment]
In most cases, you don't need to explicitly use progress/error states, since you can simply check the prop, and display some progress/error indicator where the component uses that state/prop.

But if you really want to have a separate area in your UI for displaying progress/error messages for multiple providers, you could indeed use `subscribeTo` and it would be really simple:
```js
// src/providers/status.js

status.subscribeTo = {};

['location', 'poi'].forEach(key => {
  status.subscribeTo[key] = ({ store }, { actionCreators }) => {
    const state = store.getState();

    actionCreators.setProgressStatus(key, state[`${key}Progress`]);
    actionCreators.setErrorStatus(key, state[`${key}Error`]);
  }
});
```

There isn't really a way around this because providers are meant separate your concerns, which of course means they have no knowledge of each other.  So connecting them in some way requires "glue" like this.  The only reason it's easier to do this with vanilla Redux is because it uses a single store, but there's a huge tradeoff there, and that is less separation of concerns and composability/reusability suffers as a result.  There are always tradeoffs in software engineering.  😉 

That said, improving error handling within replication is definitely near the top of my todo list.

**Comment by FredyC** [comment]
I think you've misunderstood me here a little. I don't want to store that progress in each provider separately. That means I cannot read those from `store`. Instead I am imagining I would be listening for action dispatch on the store of those target providers and update store for `status` component based on that. But yea, thanks for example, I think this should help me enough. I will just call `store.subscribe` there and watch for particular actions that are changing progress or yielding errors.
