### ISSUE TITLE
Does this work with server-side rendering?

### ISSUE THREAD

**Issue by bman654** [loggur/react-redux-provide#4]
Reading through the code, it doesn't *seem* like it would.  By not making use of `Context`, we are effectively assigning the stores as global variables (actually the stores are local properties of the providers, but the providers are assigned statically to the components).

This means that for server-side rendering, there is no good way to use different stores for different requests.  It seems like we really need to differentiate between assigning the static assignment of the providers (which implement all of the actions,reducers,selectors), and rendering the components with a specific set of stores those providers would access.

Am I misunderstanding something here?

**Comment by timbur** [comment]
Server rendering and different stores for different requests should work, but not the way you're used to.    I'll try a few things with this when I get a chance and get back to you.  :)

**Comment by timbur** [comment]
Hey sorry for the delay in getting back to you.  Been busy, holidays, etc.  `v5.0.0` should allow you to easily render things on the server.  If you can wait another day or two though I'm going to release another package to make that portion of it extremely simple.

But for now the API is roughly the same except that `assignProviders` has been removed so that you no longer have to do that, everything gets assigned automatically as the components are instantiated.  All you have to do now is basically:
```js
import { renderToString } from 'react-dom/server';
import { App } from './components/index';
import providers from './providers/index';
import getProvidedState from './yourOwn/getProvidedState';
import wrapWithDocument from './yourOwn/wrapWithDocument';

// let's export some middleware for Express
export default function middleware(request, response, next) {
  getProvidedState(request, function(err, providedState) {
    const context = { providers, providedState };
    const appHtml = renderToString(<App { ...context } />);
    const documentHtml = wrapWithDocument(appHtml);

    response.send(documentHtml);
  });
}
```

I don't really like what I had to do internally to make this work the way I wanted as I'm now "abusing" `context`, but maybe when the React team improves upon the whole `context` paradigm a bit more, it will seem less hacky to me.  I think what we have here now is close to an optimal design, so I'll try to give them some feedback in that area after I've dug into it further.

That said, `v5` should work perfectly now with SSR, plus I like the new API (everything is assigned automatically, plus a couple of other cool benefits) much better than what we had for `v4`.  Check the changes to the main README updates for more details.  :smile:

**Comment by bman654** [comment]
Yeah that looks better.  Thanks.

I don't have a problem with the way react-redux provides access to the
store via a wrapper component.  I mean there's nothing wrong with something
like:

```es6
const appHtml = renderToString(<Provider providers={providers}
state={state}><App /></Provider>);
...
```

It seems like it provides a nice entry point to put the pieces into React
`context` without "abusing" it...

Anyway, thanks for your work.

**Comment by timbur** [comment]
`react-redux`'s `Provider` component seems a bit unnecessary to me, adding logic that could have been easily included with `connect`, and I believe it's limited to one store which can't be changed and probably won't play well will multiple contexts.  I could be wrong about that last part, but in any case, I prefer a more decoupled (and automatic!) design without all of the extra boilerplate (more directories to manage, containers, more code, etc.) added by `Provider` and `connect`.  :+1: 

Please LMK if you have anymore concerns/questions!

**Comment by timbur** [comment]
Hey check out [`provide-page`](https://github.com/loggur/provide-page) and [`bloggur`](https://github.com/loggur/bloggur) for how to automatically use server-side rendering (among some other pretty useful stuff)!
