### ISSUE TITLE
Suggestion: Avoid automagical name-matching, use functional mappings.

### ISSUE THREAD

**Issue by sompylasar** [loggur/react-redux-provide#8]
Probably, as a future development, there could be an option to map props to providers manually, not automagically, if that's not against the concept. Could be useful for more predictability and decoupling from specific provider and reducer names.

@timbur What do you think?

**Comment by timbur** [comment]
Good idea! There actually isn't any magic to it, which will hopefully be clear in my next (shorter) write-up. It's literally just a single loop that compares the propTypes to the provider's actions and reducers. I like this idea though so I'll think about what might be the best method to explicitly map things. There is actually already a way to do it but I'll need to take a closer look at possibly improving the API.

**Comment by timbur** [comment]
@sompylasar Does [my latest post on medium](https://medium.com/@timbur/provide-redux-actions-and-reducers-to-react-components-automatically-1edc257eed11) help things seem less magical?

And what do you think would be a potential use-case and an ideal API for what you're asking?  The earliest version of this library did actually allow you to explicitly assign providers to components, but I removed it because it added unnecessary boilerplate.  So now that I've thought about it some more, I'm not entirely sure how necessary it would be to put that functionality back into this library plus the ability to remap action keys and/or reducer keys.  If you need to remap action keys and/or reducer keys, it would be as easy as this:
```js
import provideSomething from 'provide-something';

const actions = {
  someRenamedAction: provideSomething.actions.someAction,
  etcEtc: provideSomething.actions.etc
};
const reducers = {
  someRenamedReducer: provideSomething.actions.someReducer,
  etcEtcEtc: provideSomething.actions.etcEtc
};
const provideSomethingElse = { ...provideSomething, actions, reducers };

export default provideSomethingElse;
```

Perhaps the best way to think about providers and their actions and reducers is in the same vein of every other import within your app - i.e., all your imports are uniquely named as well.

**Comment by timbur** [comment]
Also consider that we have provider factories like [`provide-array`](https://github.com/loggur/provide-array) and [`provide-map`](https://github.com/loggur/provide-map) for common data structures that are likely to be used multiple times within the same app, and thus need unique keys.

**Comment by sompylasar** [comment]
Reading...

> And reducers are mapped such that components will always have the current state of the provider’s relevant reducers.

Reducers have no state, it's the store which has one.

**Comment by sompylasar** [comment]
> And what do you think would be a potential use-case and an ideal API for what you're asking? The earliest version of this library did actually allow you to explicitly assign providers to components, but I removed it because it added unnecessary boilerplate. So now that I've thought about it some more, I'm not entirely sure how necessary it would be to put that functionality back into this library plus the ability to remap action keys and/or reducer keys.

Right, I see.

> If you need to remap action keys and/or reducer keys, it would be as easy as this:

But if you have an app with 50+ providers, and then some day you need to reuse 10+ of them in the next app, I doubt you'll want 10+ renaming modules like in this easy example.

So you should plan ahead for the actions and reducers names -- prefix them, make them unique etc. -- to avoid such boilerplate later. From both articles this is not obvious, because there is just `count`, `increment` and `decrement` -- not `providersExampleAppCount`, `providersExampleAppCountIncrement`, `providersExampleAppCountDecrement`.

**Comment by sompylasar** [comment]
BTW, your second post is great and useful, too.

**Comment by timbur** [comment]
In summary, the best thing to do is:
- Think of providers `actions` and `reducers` as any other `import` statement, but specific to components of course, and always up-to-date state.
- Use provider factories for semi-common data structures so that keys can easily be unique.
